### ISSUE TITLE
Custom icons should imply path relative to project

### ISSUE THREAD

**Issue by freakboy3742** [pybee/toga#103]
If you specify a system icon, the path name is given relative to the toga resources directory. However, if you specify a custom icon, you have to specify a full path. This should be a relative path, relative to the project directory (or a project resource directory)

**Comment by sjlehtin** [comment]
I can take a look.

**Comment by sjlehtin** [comment]
@freakboy3742 I'm using icons like `icon = toga.Icon('testicon.png')`.  However, I get an exception
`
AttributeError: 'Icon' object has no attribute 'layout'
`

Am I doing something obviously wrong?

**Comment by ashwani010** [comment]
whats the current status of this issue ? can anyone guide me how to proceed ?

**Comment by freakboy3742** [comment]
This has been resolved as part of #288.
