### ISSUE TITLE
Tree methods are not implemented in base classes

### ISSUE THREAD

**Issue by tonybaloney** [pybee/toga#104]
In the Toga demo project, the cocoa tree widget is implemented, but the Tree widget in the base project does not have same the method signatures (or any for that matter). 
From what I've seen it's the only widget to be completely missing methods in base, is this by design?

**Comment by freakboy3742** [comment]
Oversight, not intention. The `interface` layer is a relatively recent addition, and not all the widgets have been refactored to use it.

**Comment by freakboy3742** [comment]
This has been resolved by a refactor of the Tree/Table data source implementation.
