### ISSUE TITLE
toga.Selection not working on mac?

### ISSUE THREAD

**Issue by shapiromatron** [pybee/toga#108]
I tried a simple hello world using a Selection object, and it doesn't appear to render my choices. 

```python
import toga


def build(app):
    box = toga.Box()

    selector = toga.Selection(items=['first', 'second', 'third'])
    selector.style.set(margin=50)
    box.add(selector)

    return box


if __name__ == '__main__':
    app = toga.App('First App', 'org.pybee.helloworld', startup=build)
    app.main_loop()
```

My items aren't rendered in the Selection:
<img width="508" alt="screen shot 2017-03-12 at 00 31 57" src="https://cloud.githubusercontent.com/assets/999952/23829249/5b9a0b86-06bb-11e7-8143-874921cb5770.png">

Any tips on how can I debug this? I'd like to contribute a fix if I get pointed in the right direction.

**Comment by shapiromatron** [comment]
I should probably add I'm on Sierra 10.12.3, and this was run using Python 3.6.0.  I had no issues with many of the other widgets.

**Comment by Ocupe** [comment]
@shapiromatron Hey, I just tested your code with the newest toga version from github (0.2.5.dev1) and it works like expected. So I think the problem has already been fixed. You can use the newest version of toga by cloning it from github and then ```pip install -e``` (1. toga core 2. toga cocoa 3. toga). If you need a step by step description let me know.

**Comment by shapiromatron** [comment]
It still doesn't appear to work using all the git repositories:

```bash
(venv)  🐳  ~/dev/denon$ pip freeze | grep toga
-e git+https://github.com/pybee/toga@014e8c275eb0655eec7294b11f3daf3354fbd264#egg=toga
-e git+https://github.com/pybee-attic/toga-cocoa@83c56ef75279730ff88e5ef9fc259a1eed9a6e54#egg=toga_cocoa
-e git+https://github.com/pybee-attic/toga-core@734d028c5ec833fd9d783763f8e83a1a4a5c3e21#egg=toga_core
(venv)  🐳  ~/dev/denon$ cd ../toga && git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
(venv)  🐳  ~/dev/toga$ cd ../toga-core/ && git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
(venv)  🐳  ~/dev/toga-core$ cd ../toga-cocoa/ && git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

However, I don't see `0.2.5.dev1` - can you walk me through where to get that?

**Comment by Ocupe** [comment]
Hey @shapiromatron , 
I also just recently learned this and I'm happy to share it with you.

All things in the pybee-attic are not under development anymore and should not be used for further development. Except if you want to reactivate them and start a new project from it.
This means that you're currently using the old versions of toga-cocoa and toga-core. The current versions of all platform integrations of toga are in the toga repository itself under ```toga/src/```.

This is the way I did it:
~~~bash
# clone from https://github.com/pybee/toga.git
git clone https://github.com/pybee/toga.git

# with your venv activated pip install toga bottom up
(venv) pip install -e toga/src/core
(venv) pip install -e toga/src/cocoa
(venv) pip install -e toga/src/iOS # if you need it
(venv) pip install -e toga
~~~

Now you should have the newest 0.2.5.dev1 version of toga. :)

**Comment by shapiromatron** [comment]
Definitely did not do that. Thanks; I was confused about pybee-attic. I'll try again tonight.

**Comment by shapiromatron** [comment]
I'm still struggling:

```bash
~/dev/denon$ pip freeze | grep toga
-e git+https://github.com/pybee/toga/@014e8c275eb0655eec7294b11f3daf3354fbd264#egg=toga
-e git+https://github.com/pybee/toga/@014e8c275eb0655eec7294b11f3daf3354fbd264#egg=toga_cocoa&subdirectory=src/cocoa
-e git+https://github.com/pybee/toga/@014e8c275eb0655eec7294b11f3daf3354fbd264#egg=toga_core&subdirectory=src/core
```

toga.__version__ is 0.2.5.dev1, but now when I run the script above I'm getting an error:


```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/shapiromatron/dev/denon/selector.py", line 20, in <module>
    app.main_loop()
  File "/Users/shapiromatron/dev/toga/src/cocoa/toga_cocoa/app.py", line 140, in main_loop
    self._startup()
  File "/Users/shapiromatron/dev/toga/src/cocoa/toga_cocoa/app.py", line 132, in _startup
    self.startup()
  File "/Users/shapiromatron/dev/toga/src/core/toga/interface/app.py", line 125, in startup
    self.main_window.content = self._startup_method(self)
  File "/Users/shapiromatron/dev/denon/selector.py", line 9, in build
    box = toga.Box()
  File "/Users/shapiromatron/dev/toga/src/cocoa/toga_cocoa/widgets/box.py", line 11, in __init__
    super().__init__(id=id, style=style, children=children)
  File "/Users/shapiromatron/dev/toga/src/core/toga/interface/widgets/box.py", line 21, in __init__
    super().__init__(id=id, style=style, children=children)
  File "/Users/shapiromatron/dev/toga/src/core/toga/interface/widgets/base.py", line 145, in __init__
    self.style = CSS()
  File "/Users/shapiromatron/dev/toga/src/core/toga/interface/widgets/base.py", line 173, in style

AttributeError: 'CSS' object has no attribute 'engine'
```

I was running the script as a module as toga recommends, but I get the same error when I just run normally as well.

**Comment by freakboy3742** [comment]
@shapiromatron Looks like you're hitting up against some recent changes that haven't been rolled through the entire codebase. A couple of weeks back, I rolled out some changes to the way styling is handled; I haven't had a chance to apply those changes to every widget in every platform.

**Comment by shapiromatron** [comment]
Not a problem. Thanks @freakboy3742 for this project and all the work you've done w/ Django! Let me know how I can help, or if I should just hold tight until things get propagated.

**Comment by Ocupe** [comment]
@shapiromatron I tried to reproduce your error without luck. But after a while I realized that I also have a up to date-GitHub version of colosseum installed. With the colosseum version from PyPi I get the same error you shared here, but with ```pip install -e path/to/colosseum``` it works like it should.

**Comment by shapiromatron** [comment]
Woohoo!  Thanks @Ocupe; that did the trick; I now get a properly working selector. I guess this issue can be closed since it's working for me on the latest github versions.

Now that I've got a dev environment; is there an issue I can help with?  Feel free to point me towards one...

**Comment by Ocupe** [comment]
@shapiromatron Nice! I don't have the power to close issues :D, but I also thing it should remain open until the 0.2.5 version of toga is pushed to PyPi. This way it maybe helps other people as well.

I don't know much about #103 but I can image it being a good starting point to get familiar with toga.
If you have questions ask away on the gitter channel https://gitter.im/pybee/general.

**Comment by freakboy3742** [comment]
@shapiromatron Awesome - glad that @Ocupe's suggestion worked. I'm hoping to push out a new set of releases in the near future so others won't hit the same problem.
