### ISSUE TITLE
Supported Platforms in `Docs » Widget Reference` have confusing data

### ISSUE THREAD

**Issue by Daniel-at-github** [pybee/toga#141]
Looking at https://toga.readthedocs.io/en/latest/reference/index.html#supported-platforms i see 
`toga.interface.widgets.box.Box` three times, with distinct compatibilities. Is it ok?

**Comment by freakboy3742** [comment]
The widget is OK; the docs are not. There's definitely a need for some cleanup.

**Comment by danyeaw** [comment]
I think the supported platforms have been recently updated as part of implementing the canvas widget and no longer have repeats or other confusing information. I think this issue can be closed.
