### ISSUE TITLE
Prerequisites for toga in README may be confusing

### ISSUE THREAD

**Issue by voltagex** [pybee/toga#145]
https://github.com/pybee/toga/blob/master/src/gtk/README.rst#prerequisites mentions the prerequisites for a *webview* component, not necessarily toga as a whole.

Solving issues like https://github.com/pybee/toga/issues/73 would be easier with better documentation.

I propose changing the section to list the complete dependencies for running toga. It may be better to eventually split it out to its own docs page if we end up listing a lot of different distros.

**Comment by glasnt** [comment]
This is a great idea! If you want to put this into PR I can merge it for you :)

**Comment by voltagex** [comment]
I actually think the prereqs section in the old readme is better than what's currently there.

https://github.com/pybee/toga/commit/ef64b91b454d43b886bdb46bd97a63822611a858#diff-28a7a21267020d9ddd13c055942b19e9L19

Any opposition to just pasting it back into the README?

**Comment by glasnt** [comment]
The history of both versions is interesting

https://github.com/pybee/toga/blame/26e876ffdce5eae480ecd6b0ec4995567287fc33/src/core/README.rst

https://github.com/pybee/toga/blame/master/src/gtk/README.rst

If you can put together a nice merge of the two that doesn't lose information, but still keeps the README concise, then I'm all for it!

**Comment by voltagex** [comment]
Went a slightly different direction. If there's anything that really needs to be kept from older versions, let me know.
