### ISSUE TITLE
Cleaning up duplicate README.rst broke setup for core module

### ISSUE THREAD

**Issue by voltagex** [pybee/toga#148]
https://github.com/pybee/toga/blob/master/src/core/setup.py#L20

```
(toga) PS C:\git\toga\src\core> pip install -e .
Obtaining file:///C:/git/toga/src/core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\git\toga\src\core\setup.py", line 20, in <module>
        with io.open('README.rst', encoding='utf8') as readme:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

I'm guessing toga needs those long descriptions for pypi, right?

**Comment by glasnt** [comment]
*cough* Yes. Let me just revert that change I made...

**Comment by glasnt** [comment]
Okay. So given our setup, we need a README for each component (https://pypi.python.org/pypi/toga-core)

We can't just blindly delete it, but we can clean them all up to be self-referencing, etc

**Comment by voltagex** [comment]
Closing this issue - I may open another one for cleaning up READMEs... safely.
