### ISSUE TITLE
WinForms: Button with no click event shouldn't crash

### ISSUE THREAD

**Issue by voltagex** [pybee/toga#152]
![image](https://cloud.githubusercontent.com/assets/159567/25554001/0eb140d4-2d06-11e7-8d1f-5bc5b4004f16.png)

If you add a button to a Toga app with no click event, clicking it causes an exception.

```
import toga

class TogaDemo(toga.App):

    def startup(self):
        # Create the main window
        self.main_window = toga.MainWindow(self.name)

        box = toga.Box()
        box.add((toga.Button(label="Crash")))

        self.main_window.content = box
        self.main_window.app = self
        self.main_window.show()


if __name__ == '__main__':
	app = TogaDemo('Toga Demo', 'org.pybee.toga-demo')
	app.main_loop()
```

Crashes WinForms, doesn't crash GTK

**Comment by obulat** [comment]
This issue can be closed.

I tried to reproduce this on Windows 10. It doesn't crash. The code I ran was:
import toga

```
class TogaDemo(toga.App):

    def startup(self):
        # Create the main window
        self.main_window = toga.MainWindow(self.name)

        box = toga.Box()
        box.add(toga.Button(label="Crash"))

        self.main_window.content = box
        # self.main_window.app = self
        self.main_window.show()

def main():
    app = TogaDemo('Toga Demo', 'org.pybee.toga-demo')
    app.main_loop()

if __name__ == '__main__':
    main()
```

In your code, you had double parentheses: 
`box.add((toga.Button(label="Crash")))`

Also, the code was trying to set an app for the main window, which already existed, for the second time, it raised an error.
`        self.main_window.app = self`

![untitled](https://user-images.githubusercontent.com/15233243/36249784-d72a28a6-124c-11e8-93f2-40d33194e008.png)

**Comment by freakboy3742** [comment]
Thanks for letting us know - it's probably been cleaned up inadvertently by some changes we made int he interface layer.
