### ISSUE TITLE
toga-demo won't run on macOS 

### ISSUE THREAD

**Issue by mpasternak** [pybee/toga#154]
## My system 
(toga) MacBook-Pro-Michala:~ mpasternak$ uname -a
Darwin MacBook-Pro-Michala.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

## My Python (in virtualenv, I got it from brew install python)
(toga) MacBook-Pro-Michala:~ mpasternak$ python
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
## My GCC
(toga) MacBook-Pro-Michala:~ mpasternak$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
## Trying to run toga-demo
(toga) MacBook-Pro-Michala:~ mpasternak$ toga-demo
Traceback (most recent call last):
  File "/Users/mpasternak/envs/toga/bin/toga-demo", line 7, in <module>
    from toga_demo.__main__ import main
  File "/Users/mpasternak/envs/toga/lib/python3.6/site-packages/toga_demo/__main__.py", line 14, in <module>
    main()
  File "/Users/mpasternak/envs/toga/lib/python3.6/site-packages/toga_demo/__main__.py", line 11, in main
    app.main_loop()
  File "/Users/mpasternak/envs/toga/lib/python3.6/site-packages/toga_cocoa/app.py", line 137, in main_loop
    self._startup()
  File "/Users/mpasternak/envs/toga/lib/python3.6/site-packages/toga_cocoa/app.py", line 89, in _startup
    self.resource_path = os.path.dirname(os.path.dirname(NSBundle.mainBundle().bundlePath))
TypeError: 'ObjCInstance' object is not callable
## My packages
(toga) MacBook-Pro-Michala:~ mpasternak$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.3)
colosseum (0.1.6)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
rubicon-objc (0.2.6)
setuptools (35.0.2)
six (1.10.0)
toga (0.2.8)
toga-cocoa (0.2.8)
toga-core (0.2.8)
toga-demo (0.2.5)
wheel (0.29.0)
(toga) MacBook-Pro-Michala:~ mpasternak$

**Comment by mpasternak** [comment]
This is where it fails: 

```python
from rubicon.objc import *                        
NSBundle = ObjCClass('NSBundle')           
NSBundle.mainBundle()
```

it gives me ```TypeError: 'ObjCInstance' object is not callable```

**Comment by freakboy3742** [comment]
Thanks for the report - it looks like Sierra has introduced something a small change that is incompatible with Rubicon 0.2.6 - see pybee/rubicon-objc#40 . If you downgrade Rubicon to 0.2.4, the demo should work; we're investigating a more permanent fix.

**Comment by selasley** [comment]
I was able to get toga-demo and the tutorials to run by changing 
        self._impl.setBackgroundColor_(NSColor.windowBackgroundColor())
in toga_cocoa/widgets/scrollcontainer.py to
        self._impl.setBackgroundColor_(NSColor.windowBackgroundColor)

**Comment by freakboy3742** [comment]
@selasley Thanks for that report; I've just pushed a new version of Toga (0.2.12) and Toga-demo that corrects for this, and the originally reported problem.
