### ISSUE TITLE
Addition of 2 empty boxes on an OptionContainer emits error from toga_cocoa [Cocoa]

### ISSUE THREAD

**Issue by Dayof** [pybee/toga#169]
This code was made to reproduce this error : https://gist.github.com/Dayof/cbc2ca87c094d924f087f4f975463987

Error emitted when runs the above code:

![toga_cocoa_option](https://cloud.githubusercontent.com/assets/8198348/26596388/eba8b552-4544-11e7-8fce-e4df08601075.png)

@freakboy3742's guess about this issue : "An OptionContainer should be able to have multiple Boxes as children; each box should become a panel on the option list. However, Boxes don’t have an underlying Widget, which would explain why you’re getting that error. You may need to duplicate some of the logic that Window has for managing containers so that OptionContainer can manipulate it’s children in the same way, introducing top level container widgets."

**Comment by freakboy3742** [comment]
Fixed by 1882277
