### ISSUE TITLE
ProgressBar doesn't appears in a Box [Core] [Cocoa]

### ISSUE THREAD

**Issue by Dayof** [pybee/toga#189]
Example code: https://gist.github.com/Dayof/528f9dc38f4178dbc25db6bab553e19a

When a progress bar is add inside of a box (bellow the label is the progress bar):

![captura de tela 2017-07-04 as 19 43 31](https://user-images.githubusercontent.com/8198348/27844002-b0c949e2-60f1-11e7-853c-ba0630bc481f.png)

**Comment by Ocupe** [comment]
@freakboy3742 I fixed it. 
@Dayof after the changes are merged it should work.
