### ISSUE TITLE
Tutorial 2: toga.Group for Gtk

### ISSUE THREAD

**Issue by Ry10p** [pybee/toga#191]
```
(scrolling.py:20344): GLib-GIO-CRITICAL **: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
Traceback (most recent call last):
  File "/home/ry/.virtualenvs/Contrib-Beware/lib/python3.5/site-packages/toga_gtk/app.py", line 139, in _startup
    self.startup()
  File "/home/ry/.virtualenvs/Contrib-Beware/lib/python3.5/site-packages/toga/interface/app.py", line 125, in startup
    self.main_window.content = self._startup_method(self)
  File "scrolling.py", line 61, in build
    things = toga.Group('Things')
AttributeError: module 'toga' has no attribute 'Group'

```

This error is pulled from the tutorial 2.
https://github.com/pybee/toga/blob/master/examples/tutorial2/tutorial/app.py
**The error is in regards to line 61.**

This is found using the linux version of toga (toga-Gtk).

I have been able to work around the issue in the mean time.

**Comment by lukemaxwell** [comment]
Same issue, tried toga 0.2.12 from pypi and 0.2.13.dev1 from github.

**Comment by Ocupe** [comment]
@Ry10p @lukemaxwell `toga.Group()` was a recent addition to Toga and it appears that it also fails for the cocoa backend. Sorry for that. This should not happen and I hope we will fix it soon.

**Comment by Ry10p** [comment]
@Ocupe 
Thank you so much!

I have spent some time looking at the GTK docs for adding widgets to Toga-GTK.

This might be a dumb question.... but, are the widgets that we are porting from GTK are coming from the Python3-GTK3 lib?

If so, is the entire lib available to be used to create new widgets for toga-gtk?

**Comment by freakboy3742** [comment]
Correct. Toga-gtk is an wrapper around what GTK provides. The intention is that the same Toga API can then be used to talk to Cocoa (on macOS), iOS, Windows Forms, or whatever other system native layer is available.

To that end - yes - everything that Gtk+ provides is fair game.

**Comment by Ry10p** [comment]
@freakboy3742 

Thank you! 
Getting a good mental map of how it all works helps me plan on what I will be coding.

**Comment by freakboy3742** [comment]
This should be resolved as a result of recent refactoring and testing.
