### ISSUE TITLE
When using multiple headings with Gtk backed Tree widget, content gets repeated

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/toga#202]
Using this code with the [briefcase-template](https://github.com/pybee/briefcase-template) and the Gtk backend:

```
import toga


def build(app):
    tree = toga.Tree(['Navigate', 'Description'])
    tree.insert(None, None, 'root1', 'Text for Root 1')
    tree.insert(None, None, 'root2', 'Text 2 for Root 2')
    return tree


def main():
    return toga.App('First App', 'org.pybee.helloworld', startup=build)
```

Expected a table view showing something like:

```
Navigate | Description
-----------------------------
root1    | Text for Root 1
root2    | Text 2 for Root 2
```
But the result is:

![first app_148](https://user-images.githubusercontent.com/37565/28293833-94ce9702-6b2c-11e7-9b24-bdc684773961.png)

I get a similar result adding a third heading with new content, the same thing gets repeated.

This was tested on Ubuntu Gnome 16.04.2 and GTK version `3.18.9-1ubuntu3.3`, Python 3.5.2.

**Comment by freakboy3742** [comment]
This should be resolved as part of the Tree data source refactor.
