### ISSUE TITLE
toga-demo throws and exception

### ISSUE THREAD

**Issue by juhaj** [pybee/toga#209]
Follonwing the Quick Start instructions on https://toga.readthedocs.io/en/latest/ results in

** (toga-demo:13985): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(toga-demo:13985): Gtk-WARNING **: Theme parsing error: gtk.css:13:32: The style property GtkRange:stepper-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(toga-demo:13985): Gtk-WARNING **: Theme parsing error: gtk.css:14:28: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/home/juhaj/venv_toga/lib/python3.5/site-packages/toga_gtk/app.py", line 116, in _startup
    self.startup()
  File "/home/juhaj/venv_toga/lib/python3.5/site-packages/toga_demo/app.py", line 55, in startup
    self.main_window.toolbar = [cmd1, toga.SEPARATOR, cmd2]
AttributeError: module 'toga' has no attribute 'SEPARATOR'

**Comment by csawyerYumaed** [comment]
see: https://github.com/pybee/toga-demo/issues/15

**Comment by flowerncsu** [comment]
This is fixed in version 0.2.15
