### ISSUE TITLE
Where to add toga examples?

### ISSUE THREAD

**Issue by cjrh** [pybee/toga#29]
This isn't a bug, but more a question about moving forward with examples.  Currently toga is a lib and toga_demo is the demonstration; however, one might imagine a different setup where there is an "examples" folder (perhaps inside toga folder?), inside which there are multiple `.py` files, each a separate GUI application in which one or more widgets are demonstrated. I can help with adding or testing Windows and Mac examples, but I don't know where to add such examples currently.  I would preferably like have at the very least one test example `.py` file per widget so that we can isolate the behaviour on multiple platforms on a per-widget basis.

**Comment by eliasdorneles** [comment]
While I agree that there is a teaching benefit to typing code instead of just running an example, I'd argue that it should be a choice for the learner.
After all, there is also a teaching benefit on taking some examples, modifying little bits and seeing what happens.
+1 for having an `examples/` folder.

**Comment by voltagex** [comment]
FWIW, I think this should be `docs/examples`.

@freakboy3742, do you have any reservations about merging @Dayof's example? (I think the comments and naming need a bit of a cleanup first).

**Comment by Dayof** [comment]
@freakboy3742 The PR need some modifications before you merging? @voltagex can you help me to improve the PR?

**Comment by voltagex** [comment]
I'm not sure - I think examples should be in an `examples/` subfolder under `docs/`, but it's @freakboy3742's layout.

**Comment by Dayof** [comment]
@freakboy3742 I think that this issue can be closed. :)

**Comment by Ocupe** [comment]
Examples have found a home here: https://github.com/pybee/toga/tree/master/examples 
More examples are welcomed!
