### ISSUE TITLE
Tutorial2 Fails with AttributeError: 'function' object has no attribute '_impl_32' (GTK)

### ISSUE THREAD

**Issue by DariusMontez** [pybee/toga#292]
I'm running `examples/tutorial2` on Ubuntu 16.04 (so I'm using the GTK platform)

Here's the traceback:
```
Traceback (most recent call last):
  File "/home/drew/projects/toga/toga/src/gtk/toga_gtk/app.py", line 130, in startup
    self.interface.startup()
  File "/home/drew/projects/toga/toga/src/core/toga/app.py", line 142, in startup
    self.main_window.content = self._startup_method(self)
  File "/home/drew/projects/toga/toga/examples/tutorial2/tutorial/app.py", line 105, in build
    app.main_window.toolbar.add(cmd1, cmd2, cmd3, cmd4)
  File "/home/drew/projects/toga/toga/src/core/toga/command.py", line 112, in add
    self.on_change()
  File "/home/drew/projects/toga/toga/src/gtk/toga_gtk/window.py", line 54, in create_toolbar
    item_impl.set_icon_widget(cmd._impl.icon._impl._impl_32)
AttributeError: 'function' object has no attribute '_impl_32'
```

I haven't spent a lot of time with images/icons in Toga, but I'll try to look into this.

EDIT:

So far, I found this.
`icon._impl._impl_32` should be `icon._impl(factory=?).native_32`
I think I can import the factory, but it seems odd to be importing the factory just to use an image. Or maybe not?

**Comment by freakboy3742** [comment]
Yup - this one is me too. The change was part of making icons visible on iOS; icons are treated as "late loaded" resources, so the factory is provided at the time the `_impl` is resolved, rather than when the icon is created. Your direction in the edit is on the right path; if it doesn't work out of the box, and you're not getting traction, I'm happy to take a look.

**Comment by freakboy3742** [comment]
@DariusMontez I think I've got this sorted in #293; let me know if that PR works for you.
