### ISSUE TITLE
AttributeError: module 'toga' has no attribute 'ScrollContainer'

### ISSUE THREAD

**Issue by RetardedGenji** [pybee/toga#306]
Can't figure it out.. toga.ScrollContainer() is not working :/
Any idea why?

   | Windows 10
   | Python 3.5.2
   | toga-core : 0.2.15

**Comment by RetardedGenji** [comment]
Also have this with `module 'toga' has no attribute 'SplitContainer'` it seems like all the classes arent working :/
 (also sorry for my bad english im french)

**Comment by DariusMontez** [comment]
@RetardedGenji Thanks for the report! Based on what I see in [toga_winforms/widgets](https://github.com/pybee/toga/tree/master/src/winforms/toga_winforms/widgets), `toga.ScrollContainer` and `toga.SplitContainer` have not yet been implemented. (Does something simpler like `toga.Box` work?)

Toga is admittedly behind on the Windows platform, so we're always happy to have help from Windows devs. If you (or someone you know!) are familiar with [Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/index), feel free to contribute :) Basically you'd be looking for a native widget that could work as a `SplitContainer`. Actually, It looks like their is a Windows Forms widget called `SplitContainer` -- might be a good place to start! 

If you do decide to contribute (and have time, of course), you can find some useful getting-started info in Toga's [contributing guide[](https://toga.readthedocs.io/en/latest/how-to/contribute.html).

**Comment by RetardedGenji** [comment]
Thx @DariusMontez  for your answer but I unfortunately can't help you with that (no time and not the level, i mean im a beginner / intermediate dev). And i don't get it  : does that mean that `toga.ScrollContainer` and `toga.SplitContainer` arent implemented only in windows even if i have these classes in my folder 🤔 ?

**Comment by DariusMontez** [comment]
@RetardedGenji No problem at all. I'll do my best to answer you question though :) The way Toga achieves cross-platform is slightly complex. We often describe Toga as having 3 layers: interface, implementation, and native.

* __Native__: We don't write the native layers; they are the API's provided by whatever platform you're running. If you're on Windows, we call Windows Forms the "native layer"
* __Implementation__: We write these (python classes). The job of "implementations" (one per widget for each supported platform ) is expose the native-layer thru a consistent API. For example, you'll find an implementation for a GTK+ Button at [`toga_gtk/widgets/button.py`](https://github.com/pybee/toga/blob/master/src/gtk/toga_gtk/widgets/button.py) and a different Mac OS Button at [`toga_cocoa/widgets/button.py`](https://github.com/pybee/toga/blob/master/src/gtk/toga_cocoa/widgets/button.py). Both classes have methods with the same _names_ (e.g. `set_on_press`), but the code for methods calls upon the native GUI library. Toga users/app authors don't use these classes directly.
* __Interface__: We write these too. These are the classes that you (the Toga user) create instances of. Behind the scenes, it will then create an instance of the write implementation class and interact with it. When you create a `toga.Button` on Windows, it (the interface) also creates a Button implementation from `toga_winforms/widgets/button.py`.

We've written an interface class for most of the widgets we plan to support (including `SplitContainer` and `ScrollContainer`, at least in the development version), but not every platform has the "implementation layer" done. If you're finding that `toga.ScrollContainer` and `toga.SplitContainer` don't exist, It might just be that they were created after your version (0.2.15). Either way, the implementation layer isn't done for windows.

Phew! That's probably more information than you asked for, but I hope it helps.

**Comment by RetardedGenji** [comment]
I don't think I understood everything but I guess I got the main part 😂 But still I can't find any solution to the problem so do you have any idea?

**Comment by DariusMontez** [comment]
@RetardedGenji Unfortunately, I've not worked with Windows myself (I'm a linux guy), so the development of Windows widgets won't progress quickly until a few other contributors join the project. You can refer to [this document] to see what widgets are supported. As we implement more widgets, more and more "no" will become "yes" :) For now, Linux and Mac OS have the best support.

**Comment by freakboy3742** [comment]
@RetardedGenji I don't know if you're aware, but your Github username would be considered offensive by many people. I'm sure it was intended as a light-hearted joke (with, I'm guessing, a reference to Overwatch), and the significance of the phrase possibly isn't obvious to a non-native English speaker. However, to those who have, or know someone with, a mental illnesses, it wouldn't be considered amusing.

The BeeWare project has a [Code of Conduct](https://pybee.org/community/behavior/code-of-conduct/) that we require all community participants to adhere to. While Github may allow this username, we don't consider it acceptable under our Code of Conduct. 

If you're intending to continue participating in the BeeWare community, we'd kindly ask you to change your username. A change in username would be required before we accepted any pull request from your account.

If you've got any questions about this, let us know; if you want to continue the discussion privately, please [contact me via email at russell@pybee.org](mailto:russell@pybee.org).

**Comment by RetardedGenji** [comment]
@DariusMontez Thx a lot for your help and taking the time to answer to my questions ^^  Will check some tricks and workaround to fix my "issue(?)" 
@freakboy3742 I don't really understanding why the hell my username change anything but well if you want i will change it x)

**Comment by RetardedGenji** [comment]
@freakboy3742 there you go ;)

**Comment by freakboy3742** [comment]
@RetardedGenji Thanks - but I didn't just mean your public profile name - I meant your *username*. Your public profile name isn't really used anywhere in Github, but your username is visible everywhere:

<img width="370" alt="screen shot 2017-12-13 at 6 54 50 am" src="https://user-images.githubusercontent.com/37345/33912933-b7079b64-dfd2-11e7-9879-7fc85bbbf17b.png">

To change your username, you need to use the "Account" tab, and click on the "change username" button:

<img width="732" alt="screen shot 2017-12-13 at 6 55 03 am" src="https://user-images.githubusercontent.com/37345/33912938-bd3e5108-dfd2-11e7-9459-5748f6edda09.png">

As for why it matters? You're signalling how you want to be known in the community. And by allowing you to participate in this community using that name, *we* as a project are signalling the behavior that we consider acceptable, and the values we hold as a community. 

Yes, it's a purely symbolic thing. But symbols are the way we signal to others what we think is important.

**Comment by obulat** [comment]
Should this issue be closed because of #370 ?

**Comment by freakboy3742** [comment]
Yup - I think you've fixed this one!
