### ISSUE TITLE
Failed to install toga-demo using pip

### ISSUE THREAD

**Issue by CaptainDaVinci** [pybee/toga#328]
## Expected Behavior

 
Install _toga-demo_ using  `pip3 install toga-demo`

## Current Behavior

Using pip to install toga-demo results in an error: 
```
$ pip install toga-demo
Collecting toga-demo
From cffi callback <function _verify_callback at 0x7fd673a14668>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement toga-demo (from versions: )
No matching distribution found for toga-demo
```

## Steps to reproduce

1. Run `pip install toga-demo`

## Your Environment

* Python Version: 3.5.3

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [X] Ubuntu 16.04LTS

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by SanketDG** [comment]
If it helps, you might want to create a new virtualenv and install fresh packages https://github.com/pyca/pyopenssl/issues/728

**Comment by freakboy3742** [comment]
You're also going to need to make sure you're using Python 3. The stack track you've shown highlights that you're running Python 2.7.
