### ISSUE TITLE
DetailedList Documentation is Missing

### ISSUE THREAD

**Issue by danyeaw** [pybee/toga#338]
## Expected Behavior

- Using DetailedList in Gtk+ should result in a NotImplementedError for Detailed List
- Also expect DetailedList to be documented in Supported Widgets and Widget Reference

## Current Behavior
AttributeError: module 'toga_gtk.factory' has no attribute 'DetailedList'

## Steps to reproduce
    $ cd examples/beeliza
    $ python -m beeliza
OR

    $ cd examples/detailedlist
    $ python -m detailedlist

## Your Environment

* Python Version (list the specific version number)
3.6.3

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [X] Ubuntu

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by yugeshk** [comment]
This patch is not looking for any Implementation of DetailedList to Gtk at the moment?

**Comment by danyeaw** [comment]
@yugeshk Well that would be a stretch goal :smile:

**Comment by yugeshk** [comment]
@danyeaw Got a nice sunday coming up - will get to it 😅

**Comment by adamyala** [comment]
I'm at the pycon 2018 pybee sprints. I chatted with @phildini and will be picking up this issue and finishing up @yugeshk 's PR.

**Comment by danyeaw** [comment]
Fixed with #482.
