### ISSUE TITLE
ProgressBar Example Requires Cleanup

### ISSUE THREAD

**Issue by danyeaw** [pybee/toga#341]
## Expected Behavior
Example should run

## Current Behavior
 - SyntaxError on line 50.
 - With that corrected, it immediately exists on in both Gtk+ and Cocoa.
 - Example is not in the cookiecutter format so that it can be run as a module, see examples/.templates

## Steps to reproduce

    $ cd examples/progressbar/progressbar
    $ python app.py

## Your Environment

* Python Version (list the specific version number)
3.6.3
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [X] OSX
  - [ ] Linux
  - [ ] Windows
  - [X] Ubuntu

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [X] cocoa
  - [ ] django 
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by DariusMontez** [comment]
I think this one falls on me.
Awhile ago I started PR #291 to give progress bars some well-deserved attention ... but then I got distracted by some more GTK Tree/Table business :) You can follow the thread for specifics, of course.  I'll take a look at completing that PR.

**Comment by danyeaw** [comment]
Excellent, thanks @DariusMontez

**Comment by danyeaw** [comment]
Closed by #291.
