### ISSUE TITLE
Doesn't seem to work at all on macOS High Sierra

### ISSUE THREAD

**Issue by albins** [pybee/toga#346]
## Expected Behavior
```python
import toga
toga.App("first app", "org.pybee.helloworld").main_loop()
```
*something happens*

## Current Behavior
```
Traceback:
/Users/albin/anaconda/lib/python3.6/site-packages/toga_cocoa/app.py in main_loop(self)
    165     def main_loop(self):
    166         # Stimulate the build of the app
--> 167         self._startup()
    168         # Modify signal handlers to make sure Ctrl-C is caught and handled.
    169         signal.signal(signal.SIGINT, signal.SIG_DFL)

/Users/albin/anaconda/lib/python3.6/site-packages/toga_cocoa/app.py in _startup(self)
     93 
     94     def _startup(self):
---> 95         self._impl = NSApplication.sharedApplication()
     96         self._impl.setActivationPolicy_(NSApplicationActivationPolicyRegular)
     97 
TypeError: 'ObjCInstance' object is not callable
```

## Your Environment
Anaconda install, macOS High Sierra 10.13.2.

* Python Version (list the specific version number)
```
$ python --version
Python 3.6.0 :: Anaconda custom (x86_64)
```

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] OSX
  - [ ] Linux
  - [ ] Windows
  - [ ] Ubuntu

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [x] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
This is a known problem with Toga on High Sierra (see #243). It's been fixed in the development version.

**Comment by albins** [comment]
Ah, I'm so sorry; I didn't see that when I searched for it. I think I might have filtered by status: open accidentally.
