### ISSUE TITLE
'Readonly' property of TextInput does not work

### ISSUE THREAD

**Issue by CaptainDaVinci** [pybee/toga#349]
## Expected Behavior

On using ` c_input = toga.TextInput(readonly=True)`, the `c_input` text field should not be editable by the user.

## Current Behavior
The input field can be edited by the user.

## Steps to reproduce

1. run the [tutorial](http://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html)

## Your Environment

* Python Version (list the specific version number) 3.5.3

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [X] Ubuntu (16.04)

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by yugeshk** [comment]
This is happening due to incomplete Implementation of Gtk+ to the latest release. Aware of this issue; I'm working on it 😄
