### ISSUE TITLE
Second (non-toy) example's layout is broken.

### ISSUE THREAD

**Issue by AnthonyBriggs** [pybee/toga#37]
Copying and pasting the second example results in the image below (everything squashed into the top right corner). This is under Ubuntu Trusty, the script is cut+pasted with no modifications.

![pybee_toga_busted_layout](https://cloud.githubusercontent.com/assets/295063/4315535/252677e4-3ef7-11e4-9555-612b443febef.png)

 Just playing around with adding some extra constraints to see if I can make it come out right / figure out what the problem actually is :)

**Comment by 00willo** [comment]
Just adding some recent information.  In running through this tutorial on Fedora 21, I experienced exactly the same behaviour.  gtk3-3.14.14-1.fc21.x86_64

**Comment by freakboy3742** [comment]
This has been corrected by moving from Cassowary (Constraint-based) to Colosseum (CSS-based) as a layout mechanism. The upcoming 0.2.0 release of the GTK+ backend will make this change available.
