### ISSUE TITLE
CSS not included in Toga doc

### ISSUE THREAD

**Issue by vishalpolley** [pybee/toga#386]
## Bug
In the latest version of Toga 0.3.0.dev8 documentation, under Backgrounds, the page [Commands, Menus and Toolbars](http://toga.readthedocs.io/en/latest/background/commands.html) has not included the CSS file [https://media.readthedocs.org/css/sphinx_rtd_theme.css](https://media.readthedocs.org/css/sphinx_rtd_theme.css) required for theme rendering.
You can navigate to the [page](http://toga.readthedocs.io/en/latest/background/commands.html) to see this bug.

**Comment by freakboy3742** [comment]
This is a known issue - see #363. It appears to be a problem with RTD itself.
