### ISSUE TITLE
Table incorrectly throwing Exception instead of None when no selection

### ISSUE THREAD

**Issue by go8ose** [pybee/toga#401]
## Expected Behavior

When you check the selection of a Table that hasn't got a selection, None is returned, as that's what https://toga.readthedocs.io/en/latest/reference/widgets/table.html says should happen.

## Current Behavior

Instead, a AttributeError is thrown:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/geoffc/venv/toga-experiment/lib/python3.6/site-packages/rubicon/objc/runtime.py", line 1033, in _objc_method
    result = f(py_self, *args)
  File "/Users/geoffc/git/toga/src/cocoa/toga_cocoa/widgets/button.py", line 14, in onPress_
    self.interface.on_press(self.interface)
  File "/Users/geoffc/git/toga/src/core/toga/handlers.py", line 61, in _handler
    result = handler(interface, **extra)
  File "table-selection-exception", line 6, in button_handler
    print("Selection: {}".format(table.selection.column_1))
  File "/Users/geoffc/git/toga/src/core/toga/widgets/table.py", line 92, in selection
    return self._selection
AttributeError: 'Table' object has no attribute '_selection'
```

## Steps to reproduce

1. Save this script:

```python
import toga

table = toga.Table(['Column 1'])

def button_handler(widget):
    print("Selection: {}".format(table.selection.column_1))

def build(app):
    box = toga.Box()

    table.data.insert(0, 'foo')
    table.data.insert(0, 'baa')
    box.add(table)

    button = toga.Button('Print Selection', on_press=button_handler)
    button.style.padding = 50
    button.style.flex = 1
    box.add(button)

    return box

def main():
    return toga.App('First App', 'org.pybee.helloworld', startup=build)

if __name__ == '__main__':
    main().main_loop()
```
2. Run it, `python example-script`

3. Without clicking "foo" or "baa", click the button. You will see an exception thrown.

## Your Environment

* Python Version (list the specific version number)
```
$ python
Python 3.6.3 (default, Nov 29 2017, 07:34:08) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
>>> toga.__version__
'0.3.0.dev8'
```
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: 10.13.3 (High Sierra)
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [x] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Fixed in #403
