### ISSUE TITLE
[GSoC] Adding widget support for Toga Android backend

### ISSUE THREAD

**Issue by anthonyabeo** [pybee/toga#408]
Google Summer of Code 2018 Project Proposal

# ADDING WIDGET SUPPORT FOR TOGA ANDROID BACKEND 
## A case of Icon, Image, Number Input, Password Input, Detailed List and switch

Name: Anthony A. Abeo
Email: anthonyabeo@gmail.com
Telephone: (+233) 020 267 2157
Address: PMB CT 3, Cantonments, Accra, Ghana 
Pybee/general username: @anthonyabeo

14/03/2018

### OVERVIEW
A quick glance at the codebase for the Toga Android backend reveals no support for a number of widgets that are supported by iOS. Among those are icon, image, switch, number input and password input. With two billion users and counting, the Android Operating System is the most popular mobile platform [1]. Hence there is a need to allow Python developers to quickly build apps for such a large market. This will be possible if there is an extensive support for all the widgets needed to build applications for Android. With this project, i aim to take the first steps towards contributing to the Toga Android backend by providing support for icon, image, switch, number input and password input widgets.

At the end of the project, i hope to implement and thoroughly test all the classes and functionality for the various widgets indicated above. In addition, i hope to provide extensive documentation for the widgets as well as provide small tutorials on how to use the widgets. All this will be done in accordance with BeeWare’s development practices while following external standards such as Python’s PEP guidelines. With the iOS backend well implemented, it will serve as a basis for the API specification needed for the Android version. In addition, some widgets such as button, box etc. have been implemented for the Android backend and will serve as a guide as well. As part of the process, i will spend time understanding the codebase better, build a couple of Android applications using the Toga Android backend, review the Android API specifications. 

Barring any unexpected events that might hinder my work on this project, i will like to state that i have no other obligations for the summer period and will be wholly committed to helping improve support for the Togo Android backend by implementing, testing and documenting widgets. In addition, i will like to continue on the project beyond GSOC to help add more widgets.

### DETAILED DELIVERABLES 
My plan is to dedicate two weeks for each widget. This will include implementation, testing, documentation and reviews.

#### 14 - 20 May and 21 - 27 May 
- Design and present Icon class to mentor. Seek approval before proceeding.
- Start implementation of class while writing unit tests for each method. Ensure that tests pass with 100 percent coverage.
- Extensively document the code. Perform code reviews with mentor.
- When all is good, merge with my master fork.

#### 28 May - 3 June and 4 - 10 June
- Begin implementing Image widget class after approval from mentor.
- Add unit tests and documentation along the way.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 11 - 17 June and 18 - 24 June
- Seek approval for design of password input widget class. Start implementation.
- Ensure 100 percent test coverage and add extensive documentation.
- Merge my development branch into my master fork.
- Mid-term evaluations of progress.

#### 25 - 1 July and 2 - 8 July
- Start implementation of number input widget. Writing unit tests for each method. Ensure that tests pass with 100 percent coverage.
- Writing detailed documentation.
- Perform code review with mentor.
- Merge my development branch into my master fork.

#### 9 - 15 July and 16 - 22 July
- Begin implementing switch widget class after approval from mentor.
- Add unit test and Documentation along the way.
- Perform code review with mentor.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 23 - 29 July and 30 July - 5 August
- Seek approval for design of detailed list widget class. Start implementation.
- Ensure 100 percent test coverage and add extensive documentation.
- Perform code review with mentor.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 6 - 12 August
- Final code review
- Test the all the widgets to ensure all tests are passing with 100 percent coverage.

### RISK ANALYSIS
For every project, there are a number of threats that could hinder progress of the project. Here i discuss potential threats and how i intend to manage the risks that come with it.

#### Identifying Threats. 

I will have access to the basic tools required to complete the project such as a computer, access to reliable internet etc. However, some threats that could potentially put the completion of the project in jeopardy are mainly human such as illness, injury and possibly death. Technical ability is not a problem as i have enough understanding of Python and basic software engineering practices to make good gradual progress albeit with help from mentors. In addition, another threat that could risk the project could be financial even though based on my estimation for the summer period, it shouldn’t be much of a problem. 

#### Managing Risks
With this in mind, i intend to put myself in the best physical, mental and emotional health condition to be able to complete the project. Moreover, i intend to have a plan that will sustain me financially during this period. Barring any unexpected events, i should be able to work on and complete the project.

### References
[1] https://expandedramblings.com/index.php/android-statistics/

[GSOC-2018-application.pdf](https://github.com/pybee/toga/files/1817275/GSOC-2018-application.pdf)

**Comment by freakboy3742** [comment]
@anthonyabeo This looks like a good first draft - thanks!

My biggest concern is around your timetable. It looks very much like you've just taken the 12 week program, split it into 6 parts, and allocated one per widget. Is that going to be an accurate reflection of the amount of time that will be required?

For example - the biggest red flag on this approach is PasswordInput. Are you *really* saying that it will take 2 weeks to implement? On every other platform, PasswordInput is a configuration option on a normal Text input - is this different on Android?

This also points at a second area where your proposal could be improved - identifying the pieces of the Android API that you'll be working with. What Android widget will you be using for NumberInput, for example? GTK provides a native NumberInput widget. Cocoa doesn't - it provides an "up/down arrow" widget to control a numeric value which needs to be combined with a text input for the purposes of a full Toga widget. On iOS, you don't need up/down arrows - NumberInput is a configuration item of TextInput that modifies the keyboard that is displayed. So - what Android widget are you going to use for NumberInput? 

And, tying the two concerns together - how will your choice of widget affect the complexity of each implementation? If NumberInput is just a re-configuration of TextInput, how will that take any more than a day or two? If it requires a complex interaction of multiple widgets (in a similar way to Cocoa), are you sure you'll be able to complete it in 2 weeks?

Lastly, what's the current state of the Android backend? Are you sure you'll be able to start on adding new widgets in week one? Are there any other concerns that need to be addressed?

One of the most important parts of this project plan is to provide evidence that you've looked into the problem you're proposing to solve and attempted to understand the complexity involved. Based on this proposal, I can see you've clearly identified widgets that aren't implemented, and that's a good start - but it doesn't demonstrate you've investigated enough to know which widgets will be easy, and which will be hard, and *why*. 

Instead of starting with the 12 weeks of the GSoC and working backwards to fill it with content, I would suggest starting with each widget and building up an estimate based on how long you think each widget will take to implement.

**Comment by anthonyabeo** [comment]
Hello Russell,

Thanks for the reply.

I have been working on improving on the draft and i need some
classification. During research i noticed that the number picker widget in
Android which the Toga number input will extend utilized a linear layout
and edit field among other things. My questions is that, if number input
(Toga) is implementing number picker (Android), must there exist an
implementation of the parent widgets (linear layout and edit field) in Toga
before this can work?

Regards,
Anthony.

**Comment by anthonyabeo** [comment]
Hello Russell,

Kindly take a look at my update. I am still struggling with determining the time frame. In addition, i made some changes to the widgets.

Regards,
Anthony.

**Comment by anthonyabeo** [comment]
Google Summer of Code 2018 Project Proposal


# ADDING WIDGET SUPPORT FOR TOGA ANDROID BACKEND 
## A case of ImageView, LinearLayout, GridLayout, NumberInput, Slider, Switch, and TableLayout
	

Name: Anthony A. Abeo
Email: anthonyabeo@gmail.com
Telephone: (+233) 020 267 2157
Address: PMB CT 3, Cantonments, Accra, Ghana 
Pybee/general username: @anthonyabeo

14/03/2018


### OVERVIEW
A quick glance at the codebase for the Toga Android backend reveals no support for a number of widgets that are supported by iOS. Among those are icon, image, switch, number input and password input. With two billion users and counting, the Android Operating System is the most popular mobile platform [1]. Hence there is a need to allow Python developers to quickly build apps for such a large market. This will be possible if there is an extensive support for all the widgets needed to build applications for Android. With this project, i aim to take the first steps towards contributing to the Toga Android backend by providing support for icon, image, switch, number input and password input widgets.
At the end of the project, i hope to implement and thoroughly test all the classes and functionality for the various widgets indicated above. In addition, i hope to provide extensive documentation for the widgets as well as provide small tutorials on how to use the widgets. All this will be done in accordance with BeeWare’s development practices while following external standards such as Python’s PEP guidelines. With the iOS backend well implemented, it will serve as a basis for the API specification needed for the Android version. In addition, some widgets such as button, box etc. have been implemented for the Android backend and will serve as a guide as well. As part of the process, i will spend time understanding the codebase better, build a couple of Android applications using the Toga Android backend, review the Android API specifications. 
Barring any unexpected events that might hinder my work on this project, i will like to state that i have no other obligations for the summer period and will be wholly committed to helping improve support for the Togo Android backend by implementing, testing and documenting widgets. In addition, i will like to continue on the project beyond GSOC to help add more widgets.

### DETAILED DELIVERABLES 
My plan is to dedicate two weeks for each widget. This will include implementation, testing, documentation and reviews.

#### 14 - 20 May 
Android Widget - android.widget.GridLayout
A layout manager that organizes it’s content in a rectangular grid. This layout is widely used as a standalone or as part of other widgets. 

- Design and present LinearLayout class to mentor. Seek approval from mentor before proceeding.
- Start implementation of class while writing unit tests for each method. Ensure that tests pass with 100 percent coverage.
- Extensively document the code. Perform code reviews with mentor.
- When all is good, merge with my master fork.

#### 21 - 27 May and 28 May - 3 June
Android Widget - android.widget.ImageView
A widget for displaying various image resources.

- Begin implementing Image widget class after approval from mentor.
- Add unit tests and documentation along the way.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 4 - 10 June and 11 - 17 June 
Android Widget - android.widget.TableLayout
The TableLayout widget arranges its children in row and columns. It implements a LinearLayout and uses several TableRow classes (each defining a row) in Android. 

- Seek approval for design of TableLayout widget class. Start implementation.
- Ensure 100 percent test coverage and add extensive documentation.
- Merge my development branch into my master fork.
- Mid-term evaluations of progress.

#### 18 - 24 June and 25 - 1 July 
Android Widget - android.widget.NumberPicker
The NumberInput widget will be based on the Android NumberPicker (NP) widget. The number picker widget utilizes a LinearLayout, ScrollView and an InputField. It comes in two flavors: 1) “the current value as an editable input field with an increment button above and a decrement button below” and 2) “the current value as an editable input field with a lesser value above and a greater value below” [2]. My implementation will follow the second approach.
- Start implementation of number input widget. Writing unit tests for each method. Ensure that tests pass 
  with 100 percent coverage.
- Writing detailed documentation. Perform code review with mentor.
- Merge my development branch into my master fork.

#### 2 - 8 July and 9 - 15 July
Android Widget - android.widget.Switch
Switch is a dual state widget that can be toggled between both states. In the Android API, the widget inherits from CompoundButton, Button, TextView. I will implement all the necessary methods for this class to allow 
- Begin implementing switch widget class after approval from mentor.
- Add unit test and Documentation along the way.
- Perform code review with mentor.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 16 - 22 July and 23 - 29 July 
Android Widget - android.widget.SeekBar
The SeekBar extends the AbsSeekBar and ProgressBar in Android. It is used to set some value by dragging a slider horizontally or vertically. 

- Seek approval for design of slider widget class. Start implementation.
- Ensure 100 percent test coverage and add extensive documentation.
- Perform code review with mentor.
- Merge with my master fork after all tests pass with 100 percent coverage.

#### 30 July - 5 August 
Android Widget - android.widget.LinearLayout
A layout manager that organizes it’s content in a horizontal or vertical form based on the orientation set by the user.

#### 6 - 12 August
Final code review
Test the all the widgets to ensure all tests are passing with 100 percent coverage.

RISK ANALYSIS
For every project, there are a number of threats that could hinder progress of the project. Here i discuss potential threats and how i intend to manage the risks that come with it.

#### Identifying Threats.

I will have access to the basic tools required to complete the project such as a computer, access to reliable internet etc. However, some threats that could potentially put the completion of the project in jeopardy are mainly human such as illness, injury and possibly death. Technical ability is not a problem as i have enough understanding of Python and basic software engineering practices to make good gradual progress albeit with help from mentors. In addition, another threat that could risk the project could be financial even though based on my estimation for the summer period, it shouldn’t be much of a problem. 

#### Managing Risks
With this in mind, i intend to put myself in the best physical, mental and emotional health condition to be able to complete the project. Moreover, i intend to have a plan that will sustain me financially during this period. Barring any unexpected events, i should be able to work on and complete the project.

### References
[1] https://expandedramblings.com/index.php/android-statistics/
[2] https://developer.android.com/reference/android/widget/NumberPicker.html

**Comment by freakboy3742** [comment]
@anthonyabeo You've cleaned up some questions, but introduced some others...

* Why the focus on LinearLayout, TableLayout and GridLayout? Why are Android layouts significant at all? Toga has it's own layout scheme; how do these new Layout widgets interact with Toga's design?

* What are you basing your time estimates on? Take, for example, Switch. You've said there's a built-in widget for this; there is on iOS and Cocoa as well. On those platforms, the Switch widget is around 50 lines of code. Are you saying it will take 2 weeks to implement 50 lines of code? What about ImageView - 2 weeks might be a more reasonable estimate there, because images can be difficult to work with... but you haven't made any mention of the Image class in your plan (the class wrapping actual image content).

**Comment by anthonyabeo** [comment]
Google Summer of Code 2018 Project Proposal


# ADDING WIDGET SUPPORT FOR TOGA ANDROID BACKEND 
	



Name: Anthony A. Abeo
Email: anthonyabeo@gmail.com
Telephone: (+233) 020 267 2157
Address: PMB CT 3, Cantonments, Accra, Ghana 
Pybee/general username: @anthonyabeo

14/03/2018


### OVERVIEW
A quick glance at the codebase for the Toga Android backend reveals no support for a number of widgets that are supported by iOS. Among those are icon, image, switch, number input and password input. With two billion users and counting, the Android Operating System is the most popular mobile platform [1]. Hence there is a need to allow Python developers to quickly build apps for such a large market. This will be possible if there is an extensive support for all the widgets needed to build applications for Android. With this project, i aim to take the first steps towards contributing to the Toga Android backend by providing support for icon, image, switch, number input and password input widgets.
At the end of the project, i hope to implement and thoroughly test all the classes and functionality for the various widgets indicated above. In addition, i hope to provide extensive documentation for the widgets as well as provide small tutorials on how to use the widgets. All this will be done in accordance with BeeWare’s development practices while following external standards such as Python’s PEP guidelines. With the iOS backend well implemented, it will serve as a basis for the API specification needed for the Android version. In addition, some widgets such as button, box etc. have been implemented for the Android backend and will serve as a guide as well. As part of the process, i will spend time understanding the codebase better, build a couple of Android applications using the Toga Android backend, review the Android API specifications. 
Barring any unexpected events that might hinder my work on this project, i will like to state that i have no other obligations for the summer period and will be wholly committed to helping improve support for the Togo Android backend by implementing, testing and documenting widgets. In addition, i will like to continue on the project beyond GSOC to help add more widgets.

### DETAILED DELIVERABLES 
My plan is to dedicate two weeks for each widget. This will include implementation, testing, documentation and reviews.

#### 14 - 20 May  - RadioButton, RadioGroup, CheckButton, Switch
Android Widgets - android.widget.RadioButton, CheckButton, ImageButton, Switch
These are common widgets and are easy to implement. Hence i am hoping to complete all four in one week.
- Start implementation while writing unit tests for each method. Ensure that tests pass with 100 percent coverage.
- Extensively document the code. Perform code reviews with mentor.
- When all is good, merge with my master fork.

#### 21 - 27 May and 28 May - 3 June - ImageView
Android Widget - android.widget.ImageView and android.graphics.BitMap
The image class will be an extension of Android’s BitMap class. This will allow for easy manipulation in ImageView.

A widget for displaying various image resources.
- Begin implementing Image widget class after approval from mentor.
- Add unit tests and documentation along the way.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 4 - 10 June and 11 - 17 June - DatePicker, CalenderView and TimePicker
Android Widget - android.widget.DatePicker, CalenderView and TimePicker
Working with time and date objects can be tricky. Hence, i would like to give some space for experimentation before proper implementation. I will have a TogaCalender class inherit from Calender to be used by the CalenderView.

- Start implementation.
- Ensure 100 percent test coverage and add extensive documentation.
- Merge my development branch into my master fork.
- Mid-term evaluations of progress.

#### 18 - 24 June and 25 - 1 July - NumberPicker, PasswordInput, Spinner, SeekBar, ProgressBar
Android Widget - android.widget.NumberPicker, PasswordInput, Spinner
This continues my attempt to make most of the common widgets available. Two weeks should be a good enough time to implement these five widgets.

- Start implementation of number input widget. Writing unit tests for each method. Ensure that tests pass with 100 percent coverage.
- Writing detailed documentation. Perform code review with mentor.
- Merge my development branch into my master fork.

#### 2 - 8 July and 9 - 15 July - NavigationView
Android Widget - android.widget.NavigationView
Very important widget. Could prove challenging as it consists of several widgets.

- Begin implementing NavigationView widget class after approval from mentor.
- Add unit test and Documentation along the way.
- Perform code review with mentor.
- Merge with my master fork after all tests pass with 100 percent coverage. 

#### 16 - 22 July and 23 - 29 July - WebView
Android Widget - android.webkit.WebView
WebView allows users to display web pages. This could be tricky considering all the nuances with HTML5 images, videos etc.

- Seek approval for design of webview widget class. Start implementation.
- Ensure 100 percent test coverage and add extensive documentation.
- Perform code review with mentor.
- Merge with my master fork after all tests pass with 100 percent coverage.

#### 30 July - 5 August 
Android Widget - android.widget.Icon, ImageButton, ToggleButton, CheckedTextView, Toast
- Implement some more widgets

#### 6 - 12 August
- Final code review
- Test the all the widgets to ensure all tests are passing with 100 percent coverage.

### RISK ANALYSIS
For every project, there are a number of threats that could hinder progress of the project. Here i discuss potential threats and how i intend to manage the risks that come with it.

#### Identifying Threats.
I will have access to the basic tools required to complete the project such as a computer, access to reliable internet etc. However, some threats that could potentially put the completion of the project in jeopardy are mainly human such as illness, injury and possibly death. Technical ability is not a problem as i have enough understanding of Python and basic software engineering practices to make good gradual progress albeit with help from mentors. In addition, another threat that could risk the project could be financial even though based on my estimation for the summer period, it shouldn’t be much of a problem. 

#### Managing Risks
With this in mind, i intend to put myself in the best physical, mental and emotional health condition to be able to complete the project. Moreover, i intend to have a plan that will sustain me financially during this period. Barring any unexpected events, i should be able to work on and complete the project.

### References
[1] https://expandedramblings.com/index.php/android-statistics/
[2] https://developer.android.com/reference/android/widget/NumberPicker.html

**Comment by anthonyabeo** [comment]
Hello @freakboy3742,

I have made some changes. Standing by for feedback.

Regards,
Anthony.

**Comment by freakboy3742** [comment]
Hi @anthonyabeo 

(Side note - you can edit the original proposal, rather than re-posting every time)

This is better, but still needs some refinement.

* Your proposal appears to be assuming you're going to be able to start working on widgets on day one of your project. Have you done any exploratory work into the current state of the Android backend? Are you sure this is a reasonable assumption (hint: it's not :-)

* Your timeline still contains 2 week chunks, covering multiple widgets. When we say we're looking for a week by week breakdown, we don't mean you need to name every week - we mean you need to tell us what you anticipate your progress to be *at the end of each week*. If you're not able to do this, it indicates to us that you haven't dug into the complexity of the problem sufficiently.

* You're making lots of reference to the Android classes involved (which is good), but no reference to the Toga classes that are involved. For example, checkbox is an example I've given in many presentations as the type of widget that toga *won't* have - because iOS, for example, doesn't have a checkbox widget. Toga widgets definitions cover a higher level of abstraction - they may, at some point, be implemented using checkbox, but they need to capture the high-level use case, rather than the specific widget that will be used to implement the widget.

**Comment by anthonyabeo** [comment]
Hello  @freakboy3742,

Kindly review the changes i have made.

Standing by for feedback.

Regards,
Anthony

**Comment by freakboy3742** [comment]
@anthonyabeo You've addressed the second point that I raised, but the first and third are still present.

Don't forget that the deadline is 4PM UTC today; if you want this to be considered, you'll need to make sure it's submitted to the GSoC website before then.

**Comment by anthonyabeo** [comment]
Hello @freakboy3742,

### "Your proposal appears to be assuming you're going to be able to start working on widgets on day one of your project."

For this point, my current draft says that the week before GSOC officially starts and the first week of GSOC will be dedicated to this purpose. That is, doing all the needed exploratory work that will help me be more productive with the project. 


### "You're making lots of reference to the Android classes involved (which is good), but no reference to the Toga classes that are involved."

I have added a number of Toga-* classes for each widget to be implemented. You said i may have addressed this issue in one of the previous correspondence. 

If there are any suggestions on how to improve these, kindly let me know.

**Comment by freakboy3742** [comment]
Unfortunately, this project was not selected for the 2018 GSoC. Thanks for applying!
