### ISSUE TITLE
Can't install from source: toga-gtk==0.3.0.dev8 not found

### ISSUE THREAD

**Issue by jedie** [pybee/toga#411]
```
$ pip install -e git+https://github.com/pybee/toga.git#egg=toga
Obtaining toga from git+https://github.com/pybee/toga.git#egg=toga
  Cloning https://github.com/pybee/toga.git to /home/jens/repos/RunCalculator-Env/src/toga
Collecting toga-gtk==0.3.0.dev8 (from toga)
  Could not find a version that satisfies the requirement toga-gtk==0.3.0.dev8 (from toga) (from versions: 0.1.1, 0.1.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.3.0.dev1, 0.3.0.dev2, 0.3.0.dev3, 0.3.0.dev4, 0.3.0.dev5, 0.3.0.dev6, 0.3.0.dev7)
No matching distribution found for toga-gtk==0.3.0.dev8 (from toga)

```

**Comment by jedie** [comment]
The installation as "editable" before https://github.com/pybee/toga/commit/c43daf931efc43e219f719a92bb2afbc07cfe069 worked, e.g.:

`pip install -e git+https://github.com/pybee/toga.git@5ffd722#egg=toga`

But before you can do that, you have to cleanup the venv from toga manually or create a fresh venv! pip was "broken" in this state :(

**Comment by freakboy3742** [comment]
Instructions for installing from source are described in our [how to contribute](http://toga.readthedocs.io/en/latest/how-to/contribute.html) documentation. 

The "toga" package doesn't actually contain any useful content - it's a stub that is used to install the various parts needed on a given platform. If you are installing from source, you need to install each of the individual components (toga-core and toga-gtk, in your case), and you don't need to install the core "toga" package.

**Comment by jedie** [comment]
Ah, now I understand. Thanks!
