### ISSUE TITLE
Error put NumberInput into nested box.

### ISSUE THREAD

**Issue by jedie** [pybee/toga#412]
e.g.:
```
import toga

class TestApp(toga.App):
    def startup(self):
        self.main_window = toga.MainWindow(self.name)
        box1 = toga.Box()

        box2 = toga.Box()

        input = toga.NumberInput()
        # input = toga.TextInput()

        box2.add(input)
        box1.add(box2)

        self.main_window.content = box1
        self.main_window.show()

if __name__ == '__main__':
    TestApp("test", "org.pybee.test").main_loop()
```
Running this will output:
```
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: NumberInput.set_alignment()
[GTK+] Not implemented: NumberInput.set_font()
[GTK+] Not implemented: NumberInput.set_font()
[GTK+] Not implemented: NumberInput.set_font()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: NumberInput.set_font()
[GTK+] Not implemented: NumberInput.set_font()
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

The **NumberInput** is not displayed: 

![grafik](https://user-images.githubusercontent.com/71315/37514420-2e6b34e4-2908-11e8-88fe-fe2737756af8.png)

If i replace **NumberInput** with **TextInput** it worked:

![grafik](https://user-images.githubusercontent.com/71315/37514392-1c13d9ae-2908-11e8-8ab4-5b463f66349a.png)

EDIT:
Work-a-round is to add **style=Pack(width=200)**
e.g.:
`input = toga.NumberInput(style=Pack(width=200))`

**Comment by freakboy3742** [comment]
Thanks for the report. If adding a `width=200` directive fixes the display, then the issue will almost certainly be with widget size hinting (the `rehint` method on the GTK backend for the widget). If that method is returning a 0 size value, then the widget may not be appearing (or rather, it's appearing, but with 0 size).

**Comment by jedie** [comment]
This also doesn't happen in last master version of toga ;)
