### ISSUE TITLE
[GSoC] Implementing Android Widgets for toga

### ISSUE THREAD

**Issue by kartik-karz** [pybee/toga#415]
# GSoC Proposal				

### " Better To Start Small Than Not At All "

# Introduction

Toga is a GUI toolkit for developing cross-platform OS native applications using python.

It works on the philosophy of writing the code once and deploying it to different platforms including Linux (gtk), Mac, Windows, mobile platforms like ios and android and can also be used to deploy to the web using django framework. 

# Problem

Toga is new and even though it has quite a good widgets for computer deployment it’s severely lacking on support for Android, and by the end of summer 2018, it will have to change since this project will work through many android widgets and provide suitable implementations, documentation and testing for them.

# Widgets considered

* TextView

* ImageView

* TextInput

* PasswordInput

* NumberInput

* Choice Options
	a) RadioButton
	b) CheckBox
	c) Switch

All the above ‘choice options’ will use the base core implementation of the switch.

* TimeInput (partial)

* DateInput (partial)

* DateTimeInput (partial)

# IMPLEMENTATION

	It is to be noted that the first five widgets have been considered after researching through many android apps to find out the most used widgets and more likely to be taken granted for any application development.

The latter part of the widgets will be provided initial stubs and more widget will be considered if time permits.

Widget specific details

### TextView

It will be implemented similar to toga core label but will have other details specific to android native implementation of it.

### ImageView

It will also be implemented according to the toga core imageview and few extra options for android implementation.

### TextInput

TextInput already has it’s stub under toga_android and I will be completing its implementation.

### PasswordInput

PasswordInput is present in toga already but it will be considered as not present as it needs its implementation, test cases and documentation.

### NumberInput

NumberInput in android is just a part of TextInput with numbers and will not be having any other buttons for increment or decrement.

### ChoicesOptions

This part clashes with toga ideology if implemented as specific core and hence will be implemented using the switch from toga to switch/checkbox in android

The part about radio button will also need to be checked since there’s no other implementation of it and will probably have to be discarded or implemented as a specific kind of button

### Other Widgets

Other widgets like TimeInput, DateInput, DateTimeInput will be provided initial stubs and other widgets will be taken if time permits.

# TIMELINE	

**Community Bonding:**  It has always been community bonding period for me so it will be just another period of time I will be able to clarify some doubts regarding its implementation.

**week 1:** Analyse the widgets implementation from the actual android java source code and note down the things to be kept in mind to avoid future conflicts

**week 2:** Start implementing the TextView widget.

**week 3:** Submit TextView and Start ImageView widget.

**week 4:** Submit ImageView.

**week 5:** Start TextInput and finish the first total testing.

**week 6:** Submit TextInput and start PasswordInput.

**week 7:** Submit PasswordInput and Start NumberInput and submit NumberInput.

**week 8:** [FIrst Buffer for any conflicts with the other summer project of asyncio support ]

**week 9:** Start ChoicesOptions and provide a utility method to use with switch such that the programmer can choose which implementation is to be provided on android if the switch is used.

**week 10:** Submit ChoicesOptions and start implementing stubs for other widgets.

**week 11:** [More widgets if time permits]

**From Week 12:** [Final testing and proper documentation on readthedocs for future developers]

_Testing and Documentation are an integral part of the development process and thus will be provided suitably_

It is to be noted that the timeline could be inaccurate or sometimes it feels that more could be accomplished in it. But I always believe that it’s better to commit less and provide more than commit more and provide less.

### Technical Difficulty and Risks

Honestly I am more concerned about the actual android widget implementation since as of now there is no concrete way to look at how the actual widget looks since the previous stable toga has a bit of different implementation and the current toga’s code has been restructured and during this summer it will also support asyncio so the rework for the widgets needs to be kept in mind during the time.

### Additional risks

* More time could be lost in a complex interdependent of widgets if any of things which might not be as expected while the actual implementation.

### Commitments:

I will be having my semester ending examinations in the week 4 and would have to thus reduce my development around that time, I have planned the timeline accordingly and thus will be able to manage it without affecting my performance.

### ABOUT ME:

I am a sophomore year UG engineering student from Bangalore, India. I have been tinkering with computers even before I learned to program and learning to program was one of the best choices I have ever made. I love automation and try to find ways to help me with my daily tasks. I do android development in my free time and have started to contribute to open source projects recently. I am a member of FSMK (Free Software Movement Karnataka under FSMI) and was a volunteer for 4CCon-17 and other free software talks, I try to attend meetups near my location whenever time permits. I have also packaged a few Debian packages.

There may be spelling mistakes and other grammatical mistakes please bear with it, I will try to edit those soon.

EDIT:
Pasted it here instead of refering it from docs
https://docs.google.com/document/d/1m4OpbQVxDs87C0DmyGBsn9b-6H6p2guKTAO4EUKNQhU/edit?usp=sharing

**Comment by freakboy3742** [comment]
@kartik-karz Could you please post this *in* Github, rather than referencing an external source? That allows everyone to see what you're proposing and provide feedback, and allows us to archive the discussion permanently.

**Comment by kartik-karz** [comment]
Okay I will do it now...

**Comment by freakboy3742** [comment]
@kartik-karz This is a good first draft; however, I do have some questions.

* Have you done any investigation on the current state of the Android backend? Is there any preparatory work that needs to be done?

* Why are TextInput and PasswordInput on your list of widgets to be implemented? Aren't they already implemented?

* What is a TextView widget? How does it fit into the Toga widget roadmap? How does it compare to the MultilineTextInput that exist on other platforms

* What is a ChoicesOptions widget? How does that fit into the Toga widget roadmap?

* Does week 1 have no tangible artefacts? How will we evaluate your progress in the first week?

* Why are weeks 8, 11 and 12 empty? It's a 12 week schedule - you don't need to add 3 weeks of buffer time. Allocate the available time and let us know what can be done. You *definitely* don't need to add buffer weeks for "testing and documentation" - the instructions you were sent *specifically* warned against that.

**Comment by freakboy3742** [comment]
Unfortunately, this project was not selected for the 2018 GSoC. Thanks for applying!
