### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by maxxst** [pybee/toga#42]
I tried every example and always get the following error:

    Traceback (most recent call last):
      File "toga.py", line 58, in <module>
        app = toga.App('Temperature Converter', 'org.pybee.f_to_c', startup=build)
    AttributeError: 'module' object has no attribute 'App'

I'm running `Python 3.4.1` on Mac OSX Yosemite and the toga-demo works fine

**Comment by freakboy3742** [comment]
Sorry to hear you've had problems. I can't say I've seen that error before; but it suggests that there's something wrong with your Toga install; can you confirm what attribute *are* available in to toga module (i.e., `dir(toga)` from a Python shell)?

**Comment by maxxst** [comment]
App seems to be there ... very confusing :(
````
In [1]: import toga
In [2]: dir(toga)
Out[2]:
['App',
 'Button',
 'CENTER_ALIGNED',
 'Command',
 'Container',
 'Dialog',
 'EXPANDING_SPACER',
 'Icon',
 'JUSTIFIED_ALIGNED',
 'LEFT_ALIGNED',
 'Label',
 'MultilineTextInput',
 'NATURAL_ALIGNED',
 'OptionContainer',
 'PasswordInput',
 'ProgressBar',
 'RIGHT_ALIGNED',
 'SEPARATOR',
 'SPACER',
 'ScrollContainer',
 'SplitContainer',
 'TIBERIUS_ICON',
 'Table',
 'TextInput',
 'Tree',
 'WebView',
 'Window',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'absolute_import',
 'alignment',
 'constants',
 'constraint',
 'division',
 'importlib',
 'os',
 'platform',
 'print_function',
 'set_platform',
 'sys',
 'unicode_literals',
 'widget']
````

**Comment by freakboy3742** [comment]
Do you get the same errors if you drop a `print dir(toga)` in your example script itself? If you're getting this on every example - can you provide the full source for tutorial 0?

**Comment by maxxst** [comment]
now I feel stupid ... the file was named toga.py -> renamed it to toga_test.py and now it works

thank you for your help though

toga still looks like something I want to work with :+1:
