### ISSUE TITLE
Make sure that all supported widgets are listed on 'Supported widgets by platform' page

### ISSUE THREAD

**Issue by tenkabuto** [pybee/toga#420]
## Expected Behavior
The [Supported widgets by platform](https://toga.readthedocs.io/en/latest/reference/supported_widgets.html) would list all widgets supported per platform.

## Current Behavior
On at least the Android platform's column, at least two supported widgets (Label and TextInput) were not listed, which contributed to the appearance of there being a lack of support for android in Toga.

## Steps to a fix
1. Figure out which widgets are supported per platform
2. Update the widgets' record files contained in the [supported_platforms subdirectory](https://github.com/pybee/toga/tree/master/docs/reference/supported_platforms)

**Comment by freakboy3742** [comment]
I think this has now been addressed; we've removed the standalone "supported widgets" page, but reorganized the widget index to include all widgets currently supported.
