### ISSUE TITLE
automate GI symlink

### ISSUE THREAD

**Issue by glyph** [pybee/toga#43]
If you have a program which is broken, you have two choices:

1. tell your users that the thing is broken and give them an elaborate rationale as to why it's broken because you're a huge nerd
2. fix it

As a huge nerd I can appreciate the appeal of the first option there, but usually the first one is a better choice :).

As such, rather than putting an "ln ..." command in the README, why not just include the workaround inside toga itself? Try the import, if it fails, try to set up the symlink and then try again.  Since the symlink is only necessary in virtualenvs, there should not be a permission problem with doing this.

**Comment by glyph** [comment]
Also, as I said on Twitter: there is a "right" answer to this problem involving setuptools metadata and pip features. Ignore that. Just literally call `os.symlink` as you're telling the users to.

(Or maybe I mean "I will do this", someone is free to hassle me to produce a PR…)

**Comment by freakboy3742** [comment]
That's a neat idea - I hadn't considered that since you're in a venv, there aren't any permission or "contaminating global install" problems... Just need to do enough to identify the OS + version, and make sure you symlink the right package. +1.
