### ISSUE TITLE
GSOC Proposal Implementing Android Widgets

### ISSUE THREAD

**Issue by ndew623** [pybee/toga#430]
# About Me
Nicholas Dewey
GitHub: ndew623
Email: dewey.71@osu.edu
Phone: (779) 861-0074

My name is Nicholas Dewey, and I am a Computer Science and Engineering major at The Ohio State University. In school I have studied C/C++ and Java. Outside of school I have also written JavaScript, Python, C#, and PHP. I love the simplicity and power of Python. However, in the past couple of years I have been preoccupied with school and my hobby of Android development. After the recent completion of my app AndroidCrypt (github.com/ndew623/AndroidCrypt), I want to dive into contributing to open source projects. I was initially attracted to BeeWare because of my love for Python. However, I applied because of the opportunity to both work with Python and use my knowledge of Android development to contribute to open source.
# Introduction
The future of computing is making its way to mobile. By some measurements, Android is already the world’s most popular operating system, and its user base will only continue to grow. BeeWare’s mission is to provide the tools to allow developers to write their applications once, and deploy it to multiple platforms, and Android’s popularity makes it one of the most important platforms for BeeWare to support. Despite this, the ability to deploy cross-platform applications to Android with BeeWare is essentially nonexistent. Two of the three major components, VOC and Briefcase, are functional. Toga widget support is the only major roadblock remaining.
# Project
My project proposal is to take the third step to making BeeWare on Android a reality by implementing Toga widgets and bringing Android support up the the same level as GTK and Cocoa. This includes not only implementing base functionality, but also the non-critical toga widget methods like set_font() or set_alignment(). Currently there are 16 Toga widgets that are not implemented on Android. I will start with the simplest widgets and use them as a learning opportunity to become more familiar with Toga. These widgets have Android counterparts with comparable APIs and are easy to implement. Most of their methods are one line calls to the Android api via self.native. I implemented 7 unimplemented methods in the existing Toga android widgets as well as a native_color method for Android in a few hours. After becoming more familiar with Toga and working full time, I think I can finish these simple widgets in a few days. Other widgets such as Tree, Table, SplitContainer, and Slider don’t have direct Android equivalents. I will implement them last, and they will take up the majority of the work time. In between are widgets like Canvas and Selection. They have Android counterparts, but the APIs don’t match up as well. Working on Android is also an opportunity to write some Android specific documentation. For example, the only place the process of building for Android is documented is in a comment on this GitHub issue (https://github.com/pybee/toga/issues/162). The instructions are good, but they are not comprehensive and a GitHub issue is not the right place for such a guide. Of course, the existing documentation will need to be continuously updated as widgets are implemented.
# Weekly Schedule

April 23 - April 28GSoC Community Bonding | During the community bonding period I can get more familiar with Toga and writing Android code in Python. The more I learn during Community Bonding, the smoother the rest of the project will go.
-- | --
April 23 - April 28GSoC Community Bonding | During this time I’ll also experiment. I’ll try implementing several widgets. I won’t be able to make a serious effort yet, but For example, NumberInput is just an extension of TextInput.
April 29 - May 5GSoC Community Bonding | Classes and finals end on May 1st. Up until then work time will be very limited. I have a busy schedule this semester. The GSoC application period has already been straining. However, after May 1st time to work won’t be an issue.
May 6 - May 12GSoC Community Bonding | This is still community bonding period. However, after three weeks it may be time to start serious coding early. If I didn’t implement NumberInput before, I’ll do it now.
May 13 - May 19 | Implement Switch and Progress bar. Switch is easy. Android already has those and they already work the same way. Android has progress bars too, but they might take a little more work. The indeterminate Android progress bar is a spinning circle that requires totally different dimensions than the determinate bar. Also, Android doesn’t have started and stopped states associated with its progress bars as Toga does.
May 20 - May 26 | Implement the resources: Image, Icon, Font, Group, Command. The most important in this list is Image. It is needed to make ImageView (scheduled for next week) work. The others on the list are nice to have but not as crucial and not included in my project proposal. During this week, whatever doesn’t get done (outside of Image) doesn’t get done. Image should be implemented with Android drawable resources. As for fonts, Android has android.graphics.TypeFace.
May 27 - June 2 | Implement MultilineTextInput, WebView, and ImageView. These all have Android equivalents. MultilineTextInput can be extended from TextInput in the same way as PasswordInput or NumberInput. The functionality of a Toga WebView appears as though it can be easily supported by Android’s WebView API.
June 3 - June 9 | Implement Slider and start work on ScrollContainer and Split Container. Slider corresponds to the Android SeekBar widget. Android has ScrollView, which is the functions exactly like ScrollContainer except that it can only have one direct child view. This can be solved by using a LinearLayout inside of the ScrollView. Split Container can be done with a LinearLayout so that each child Layout has a layout weight of 1.
June 10 - June 16First evaluation | Finish ScrollContainer and SplitContainer. Slider doesn’t take more work than other widgets that are to be developed in half a week. However, this is the first time I’ll be working with container widgets so I’m allowing an extra week for them.
June 17 - June 23 | Implement Table, and start working on Canvas. Android has both TableLayout and GridView that are candidates for implementing toga.Table. They both have pros and cons. I think Table and Canvas will take more time than previous widgets. While the implementation of Table shouldn’t be difficult, the best way to do it isn’t obvious immediately. Some of the calls to toga.Canvas methods will have to be implemented with the right combination of Android’s Canvas API calls and probably some geometry. For example, Android has no bezier_curve_to() equivalent. Also, it takes x, y coordinates as arguments for where each drawing starts, rather than having a moveTo() method.
June 24 - June 30 | Finish Canvas. I’m giving myself another week with Canvas because implementing one set of drawing methods with another, using geometry, and keeping track of the toga.Canvas’s penpoint all sound bug prone.
July 1 - July 7 | Implement Selection, Tree, and DetailedList. These all share a common trait. Their Android equivalents (Spinner, ListView, and ExpandableListView respectively) all need a ListAdapter. A ListAdapter stores the data and defines how each data item gets turned into a listview item. Because Toga seems to limit its list items to Strings, Android’s built in implementations of ListAdapter will probably work. DetailedList poses another issue. Toga’s DetailedList supports deleting, and updating. However, the UI for this functionality does not exist by default in Android’s ListView. This will require design decisions and custom UI. Are list items swiped away? Does each item have a delete button? Should there be checkboxes and a single delete icon in the action bar?
July 8 - July 14Second evaluation | Continue work on DetailedList’s delete and update functionality. Pulling a list down to update it is best implemented by Android’s SwipeRefreshLayout. I’ve never used it before. This may be an additional challenge.
July 15 - July 21 | Finish DetailedList. Start OptionContainer.
July 22 - July 28 | Implement OptionContainer. There are couple of options for OptionContainer. One is to create tabs (see this example https://i.stack.imgur.com/77PlQ.png). They look good, and it is a common design in Android applications. It would be nice to make this feature available to Toga applications. The problem is that those tabs are tied to the ActionBar. Consequently, I don’t think it would be possible to nest OptionContainers inside other containers this way. Alternatively, a custom view using Android’s RadioButtons (styled not to have an ugly dot next to them of course) would do the trick.
July 29 - August 4 | Finish working on OptionContainer.
August 5 - August 11Coding period ends | The GSoC coding period ends on August 6th. I’m sure I can find something useful to do on August 5th. Creating a how-to-guide for the documentation on compiling Toga apps for Android is part of my proposal and it shouldn’t take more than a day.

# Risk Analysis
This schedule assumes a quick and steady development pace. That is unrealistic. The implementation of at least one widget will go wrong and derail the schedule. However, some widgets may be easier than expected and help counterbalance the ones that cause problems. To be clear, I do not intend for this schedule to be an unattainable ideal. I did however, keep in mind that if progress slipped, the project could still produce valuable results. A nice feature of this project is that it has a lot of small deliverables. Even if I fail to meet my own goals, the Toga project will still get improved Android widget support. One goal when making the schedule was to put the the widgets most likely to be problematic and take the most time towards the end. The widgets of particular concern are Canvas, DetailedList, and OptionContainer (for reasons that are mentioned in the schedule). That way, if one or more of them takes much longer than expected, only those few widgets are at risk of not being completed. In the event that I am behind schedule, cuts can be made to get back on track. For example, if most of the functionality of Canvas is completed in a week, but I spend the next week failing to implement quadratic_curve_to(), then it would make sense to abandon it and move on next week.

**Comment by freakboy3742** [comment]
@ndew623 This is a good first draft. My overall impression is that this is *very* ambitious - you're covering a lot of widgets in a very short time. That said, you've also got Android experience, and you're restricting yourself to implementing existing interfaces, which is the easier part of the process. 

The single strongest thing you could do to strengthen this proposal would be to convince me that your estimates of "days per widget" are accurate. I'm not sure I can suggest anything specific that would achieve this, but at the moment, it's only really addressed tangentially (stating past experience etc). 

Some more specific questions/comments:

* Have you validated the current state of the Android backend? The 0.3.0 branch did a bunch of refactoring - are you certain you're going to be able to start straight away implementing widgets? (hint - you won't :-)

* Implementing ImageView before you have access to an Image resource seems completely bass-ackward. 

* The discussion about ListAdapter is interesting; I'd feel a little more confident about your estimate if you were able to give a comparison between ListAdapater and Toga's ListSource, and how that mapping will play out in practice.

* Some of the widgets cross 2 weeks of the schedule, which makes sense in terms of the effort involved; however, your proposal would be stronger if it gave a better sense of *why* a particular widget will take 2 weeks, and what progress we can expect to see at the end of the first week.

**Comment by ndew623** [comment]
>The single strongest thing you could do to strengthen this proposal would be to convince me that your estimates of "days per widget" are accurate.

I've tried to address this issue somewhat in the project overview, and risk analysis. In risk analysis I discuss why I made it such a tight schedule. 

>Have you validated the current state of the Android backend? The 0.3.0 branch did a bunch of refactoring - are you certain you're going to be able to start straight away implementing widgets? (hint - you won't

Apparently not. Maybe its something I can figure out during the community bonding period. My updated proposal doesn't mention this yet, but I'll try to figure it out tomorrow.

>Implementing ImageView before you have access to an Image resource seems completely bass-ackward.

Fair enough.

>The discussion about ListAdapter is interesting; I'd feel a little more confident about your estimate if you were able to give a comparison between ListAdapater and Toga's ListSource, and how that mapping will play out in practice.

I don't know that they will interact much. Toga's interface needs to produce a ListSource and Android needs a ListAdapter. That seems to necessitate keeping two concurrent versions of the list data in each one.

>Some of the widgets cross 2 weeks of the schedule, which makes sense in terms of the effort involved; however, your proposal would be stronger if it gave a better sense of why a particular widget will take 2 weeks, and what progress we can expect to see at the end of the first week.

I've restructured the schedule. I think addresses this better than before.

**Comment by freakboy3742** [comment]
Unfortunately, this project was not selected for the 2018 GSoC. Thanks for applying!
