### ISSUE TITLE
Unable to run freakboy3742/avatar tutorial code.

### ISSUE THREAD

**Issue by RatanShreshtha** [pybee/toga#433]
I am trying to run the code from https://www.crowdcast.io/e/beeware tutorial but I am getting following error.

```
Traceback (most recent call last):
  File "/home/ratan/.local/share/virtualenvs/avatar-qctsTVmP/lib/python3.6/site-packages/toga_gtk/app.py", line 140, in startup
    self.interface.startup()
  File "/home/ratan/Desktop/projects/avatar/avatar/app.py", line 48, in startup
    self.avatar = toga.ImageView()
  File "/home/ratan/.local/share/virtualenvs/avatar-qctsTVmP/lib/python3.6/site-packages/toga/widgets/imageview.py", line 22, in __init__
    self._impl = self.factory.ImageView(interface=self)
AttributeError: module 'toga_gtk.factory' has no attribute 'ImageView'
```
* Python Version (3.6.4)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [x] Linux - distro:  Fedora - version: 27
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by danyeaw** [comment]
@RatanShreshtha Thanks for submitting the issue! Unfortunately, ImageView is not yet supported in Gtk+. It is actually one of the few widgets that isn't yet supported for this backend. Are you interested in getting involved to help fix this?

1. To get started and make your first contribution you could edit the imageview.rst to show that ImageView is not supported in Gtk+, the docs are currently not correct. This could be a standalone Pull Request.
2. Once you get your feet wet with your first contribution, you could implement ImageView in Gtk+. We would be happy to help assist and coach you along towards your first code contribution.

There is more information about [Contributing](https://pybee.org/contributing/how/first-time/).

**Comment by RatanShreshtha** [comment]
Thanks @danyeaw  
I would be happy to contribute to toga project in any way, although I will need help and guidance for implementing ImageView in Gtk+.

**Comment by RatanShreshtha** [comment]
@danyeaw  I have updated the doc and created a pull request.

**Comment by danyeaw** [comment]
Thanks @RatanShreshtha for the PR! I'm going to go ahead and close this issue since we don't normally keep them open for widgets not yet implemented. First step for implementing ImageView in Gtk+ will be to determine if PyGObject support something with similar functionality. If you have questions I would be glad to discuss on gitter.
