### ISSUE TITLE
no widget seen on android app

### ISSUE THREAD

**Issue by onrkrt** [pybee/toga#445]
I am trying to make this example 

https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html

everything is fine but when I opened the app on my phone there is nothing to see, only an header which writes my app name but the button doesn't seems

**Comment by ArchKudo** [comment]
@onrkrt this is the expected behaviour, quoting directly from _What should happen_ section present at the bottom of the tutorial:

> When the application runs, you should see a window with a title of “Hello World” appear. The window won’t contain any content - but it will be a native application, with a native icon in your task bar (or wherever icons appear on your platform).

**Comment by freakboy3742** [comment]
@ArchKudo Ah - thanks for clarifying that... I really should know what is in our tutorials, shouldn't I :-)
