### ISSUE TITLE
Revising Table contents / Dynamic Table Data

### ISSUE THREAD

**Issue by bschollnick** [pybee/toga#45]
Folks,

I'm trying to convert an application to use Toga, and I don't see any way to refresh the table, after creation?  Is there a way to remove a row from a table?  I don't see any obvious method to do so, but I am maybe missing something obvious?

**Comment by freakboy3742** [comment]
You're not missing anything obvious; the API for the data source of tables and trees needs some work.

**Comment by freakboy3742** [comment]
The Table/Tree APIs have now been revised, resolving this issue.
