### ISSUE TITLE
Getting text of the Multi-line Text Input

### ISSUE THREAD

**Issue by stantonxu** [pybee/toga#464]
## Expected Behavior

I read through the API reference, seems the "value" is to set the text of the Multi-line Text Input. However, after user types in the Input, the "value" is not updated.

We need a method to get the input from the Multi-line Text Input box.

## Current Behavior

"value" is not updated after user types.

## Your Environment

* Python Version (list the specific version number)

3.6.4

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [*] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [*] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by stantonxu** [comment]
Per @freakboy3742 's suggestion, I created a Pull Request #465 for my implementation.

**Comment by freakboy3742** [comment]
Fixed in #465
