### ISSUE TITLE
requirements_dev.txt missing

### ISSUE THREAD

**Issue by 00willo** [pybee/toga#49]
I'm guessing that this should contain, things like, tox etc.

I can submit a pull request for this, if this is confirmed.  If not, then internal/contributing.rst needs updating.

**Comment by danyeaw** [comment]
The contributing information for Toga is here: https://toga.readthedocs.io/en/latest/how-to/contribute.html
The README also has information about what is required to be installed through a package manager, I don't think a requirements.txt is needed at this point.

**Comment by freakboy3742** [comment]
I'm guessing you're looking at an older checkout; internal/contributing.rst no longer exists, and there shouldn't be a need for a requirements file - toga is a self contained package, so any dependencies should be (and are, AFAIK) listed in setup.py.
