### ISSUE TITLE
Desire to support python <= 2.5???

### ISSUE THREAD

**Issue by 00willo** [pybee/toga#50]
Here is just the important end bit of the exception generated when running tox through py34:
```
  File "/home/willo/git/toga/tests/test_attribute.py", line 6, in <module>
    from toga.constraint import Attribute, Constraint, InvalidConstraint
  File "/home/willo/git/toga/toga/__init__.py", line 75
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
ERROR: InvocationError: '/home/willo/git/toga/.tox/py34/bin/python setup.py test'
```

Now changing to ```ImportError as e``` will work for python2.6+.  Is there any desire for toga to support <= 2.5?

There's maybe some other instances of this, which I'll search for when submitting a pull request.

**Comment by tritium21** [comment]
2.5 is almost a decade old.  It is probably worth while to drop it.  2.6+ seams to be the most widely accepted target for minimum versions these days.

**Comment by freakboy3742** [comment]
This has now been done; Toga is Python 3.4+ only.
