### ISSUE TITLE
Overflow error with toga-demo on windows

### ISSUE THREAD

**Issue by Badg** [pybee/toga#53]
Fresh install of toga-demo, with successful install of all dependencies. Running in anaconda on 64-bit windows 7 with 64-bit python. Toga-demo could not execute, threw an OverflowError and then an AttributeError -- see screenshot.

![toga-overflow](https://cloud.githubusercontent.com/assets/6155386/11006043/61aa583c-8476-11e5-8c50-ff91696c60c0.PNG)

**Comment by freakboy3742** [comment]
Thanks for the report. Toga on Windows is fairly primitive - it hasn't got all the widgets necessary to handle the full toga-demo - so you haven't done anything wrong here. Windows is an area that I accept as important, but it's lower on my personal list of immediate priorities; if anyone *is* motivated to work on Windows support, especially if they have expertise on native Windows APIs, I'd deeply appreciate the help.

**Comment by ginoskotheon** [comment]
I'm kind of a noob programmer but I like to tinker around. One of my goals is to help the user experience of Python on Windows. That said, I am a noob (maybe more like a higher level noob). If anyone can point me in a good direction for learning Windows APIs, I'll gladly do the footwork and begin contributing the best I can. Thanks ahead of time.

**Comment by freakboy3742** [comment]
@ginoskotheon If you're in a position to help out, that would be amazing!

Unfortunately, I don't know where to point you for learning Windows APIs; I haven't used Windows in any serious capacity for many years now. 

I've got two suggestions for getting started - both from a "here's a goal" perspective. If you can get to that goal, I can point 

1. Implement Toga [tutorial 0](http://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) (and maybe [tutorial 1](http://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html)). Do this in several phases:
    a. Implement the app using a completely native Windows API and language.
    b. Extend that app in such a way that it exposes a raw C API.
    c. Implement the app using Python `ctypes` invoking that C API.

2. Work out what wrapping is necessary to distribute this windows app as an installable app that behaves the same way that a normal Windows app works.

For point (1), I'm assuming that having a C API invoked over `ctypes` will be the easiest way to invoke a C# API; however, that may not be the case. Essentially, the task here is to investigate, and see what works and what doesn't. The only goal I have is that the end-user must have a 0 compilation install path. It doesn't matter if the *developer* needs to compile something, as long as it can be wrapped up as a wheel and distributed as a binary that Just Works(tm).

For (2), see [pybee/Python-macOS-template] for an example for what I mean in a macOS context; I'm looking for the analog of that for windows, which may involve writing an installer script of some kind. I'm assuming WiX or NSIS will be needed here.

**Comment by ginoskotheon** [comment]
@freakboy3742 Thanks for the response and the guidance. Exactly what I needed. I will begin putting in the time and thought. It will take me a while, probably. But I'm really pumped to help in anyway I can. And if anyone out there is better at this than I am, I would love to collaborate.

**Comment by freakboy3742** [comment]
Closing this ticket in favour of general improvement on toga-win32/toga-winrt
