### ISSUE TITLE
A single column table leads to only showing first letter of value

### ISSUE THREAD

**Issue by sbeaumont** [pybee/toga#539]
## Expected Behavior

Table like this:
**Filename**
xxx
yyy
zzz

## Current Behavior
**Filename**
x
y
z

## Steps to reproduce

Use toga.Table(headings=['Filename'], data=['xxx', 'yyy', 'zzz'], on_select=self.handle_name_select)

## Analysis
The problem seems to be in the ListSource class.
`def _create_row(self, data):
        if isinstance(data, dict):
            row = Row(**data)
        else:
            row = Row(**dict(zip(self._accessors, data)))
        row._source = self
        return row'

In list_source.py line 56 it says:

`row = Row(**dict(zip(self._accessors, data)))`

but the data parameter is a string when using a list of strings as data, leading to the zipping of the individual characters. When passing in the data as [('xxx',), ('yyy',), ('zzz',)] the error does not occur.

So either the API should make it explicit that it expects a list of lists, or handle the data-is-a-list-of-strings case correctly

**Comment by DariusMontez** [comment]
@sbeaumont Your confusion led me to an interesting discovery. Consider this:

To render data to a *Tree* widget, you use a *Tree*Source.
To render data to a *Table* widget, you use a ... ListSource?

So you see, the purpose of a ListSource is really to store a row of lists, which is a *table*.

TreeSource actually was called "DictSource" when it was first fleshed out, and there was a resemblance to Python's `list` and `dict`. Dict became Tree, but List never became Table.

Combined with the fact that the docs for Tree and Table are way wrong (written before the existence of data sources), these two widgets can be quite flustering to use.

My personal opinion is to steer clear from handling a special case. The either way, the docs need to updated, and I would recommend renaming ListSource to TableSource. @freakboy3742 I always like to get your input before renaming so I don't introduce even more confusion :-)

 I can see that displaying a single column or 'list' is a fairly common task, and we could easily create a simplified version of Table called List that can be created from a flat `list`. Then again, we already have a widget called DetailedList, but it uses ListSource and therefore is also a table.

An argument can be made, however, for keeping the current naming of `ListSource`. Consider a Contacts app that displays each person's profile photo to the left of their name. Structurally, this is a table with two columns; one for the image, and the other for the name text. But semantically it is a "list of contacts", not a table of contacts. In this case, ListSource and DetailedList seem to be named appropriately.

**Comment by DariusMontez** [comment]
I'm tinkering with this. @freakboy3742, are strings the only type that get the special treatment, or should ListSource handle flat lists of other types?

```python
# flat list of strings - Yes
ListSource(["xxx", "yyy", "zzz"])

# flat list of numbers?
ListSource([100, 200, 300])

# flat list of instances implementing __str__?
List Source([MyObject(1), MyObject(2), MyObject(3)])
```

**Comment by freakboy3742** [comment]
@DariusMontez Hrm... I could go either way; but I think being as generous as possible in what we accept could be a good thing.
