### ISSUE TITLE
No module named 'toga.style'

### ISSUE THREAD

**Issue by mc436572** [pybee/toga#551]
## Expected Behavior

when I try to run "A slightly less toy example",   find err: 
ModuleNotFoundError: No module named 'toga.style'

## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)
py 3.6
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [y ] Windows - version: win10  64bit
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
You've almost certainly run the tutorial for Toga 0.3.0 (the current development version), but installed 0.2.15 (the current stable version).
