### ISSUE TITLE
No module named 'toga.style' for the toga version on pypi

### ISSUE THREAD

**Issue by stantonxu** [pybee/toga#553]
## Expected Behavior

The toga example should be running ok with the `toga` from `pypi` in a clean venv.

## Current Behavior

While running the `detailedlist` example https://github.com/pybee/toga/tree/master/examples/detailedlist in a clean venv with `toga` installed from `pypi`, it says
`ModuleNotFoundError: No module named 'toga.style'`

## Steps to reproduce

1. Create a clean venv

2. pip install toga

3. python -m detailedlist

## Possible root cause
**The toga version on pypi is 0.2.15. I downloaded the toga 0.2.15 source code from github, it doesn't have the `style` folder under the `src/core/toga`**

## Your Environment

* Python Version (list the specific version number)
3.6.4

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: 10.12.4
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [x] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
The introduction of `toga.style` was part of the changes introduced in 0.3. The 0.2 branch (which is the current stable release on PyPI) doesn't have that API.

**Comment by stantonxu** [comment]
Then in the readme.md file, for example https://github.com/pybee/toga/tree/master/examples/detailedlist, should we change it to 
```
To run this example:
$ pip install toga==0.3.0.dev8 $ python -m detailedlist
```

**Comment by CTheCheese93** [comment]
The current error that I get with `pip install --pre toga` is:

`pip install --pre toga
Collecting toga
  Using cached https://files.pythonhosted.org/packages/04/73/3ded37ce19d9657be425fffd1ee76d7cde26395baab17c01548db0230927/toga-0.3.0.dev11-py3-none-any.whl
Collecting toga-gtk==0.3.0.dev11; sys_platform == "linux" (from toga)
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Collecting gbulb>=0.5.3 (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
  Using cached https://files.pythonhosted.org/packages/40/ee/8daf797cda4ffe7724b9d47cbb5e2b44ca6235764622d163c586bd9bd7c5/PyGObject-3.32.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting toga-core==0.3.0.dev11 (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Building wheels for collected packages: pygobject
  Building wheel for pygobject (PEP 517) ... error
  ERROR: Complete output from command /home/cthecheese/Programming/Anaconda3/envs/PyRoot/bin/python /home/cthecheese/Programming/Anaconda3/envs/PyRoot/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpzg3ely_i:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  creating build/lib.linux-x86_64-3.7/gi
  copying gi/_error.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_compat.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/types.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/module.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_option.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/importer.py -> build/lib.linux-x86_64-3.7/gi
  creating build/lib.linux-x86_64-3.7/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.7/gi/repository
  creating build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.7/gi/overrides
  running build_ext
  Package gobject-introspection-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gobject-introspection-1.0' found
  Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.46.0')' returned non-zero exit status 1.
  
  Try installing it with: 'sudo apt install libgirepository1.0-dev'
  ----------------------------------------
  ERROR: Failed building wheel for pygobject
  Running setup.py clean for pygobject
Failed to build pygobject
ERROR: Could not build wheels for pygobject which use PEP 517 and cannot be installed directly
`

However, `pip install toga==0.3.0.dev8` does work.
