### ISSUE TITLE
'toga_gtk.factory' has no attribute 'DetailedList'

### ISSUE THREAD

**Issue by hamzzy** [pybee/toga#555]
## Current Behavior

when ever i import and detailedlist  and use it prompt
'toga_gtk.factory' has no attribute 'DetailedList'

## Your Environment

* Python Version (list the specific version []

- [ ] number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] @macOS - version: 
  - [ -] Linux - distro:   - version: ubuntu 18.04
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [- ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by stantonxu** [comment]
Which version of toga do you use?

**Comment by freakboy3742** [comment]
Detailed list isn't implemented for the GTK backend yet; hence the error.

**Comment by stantonxu** [comment]
@hamzzy , as @freakboy3742 indicated, if you look into the source code, DetailedList is not implemented yet for GTK.
