### ISSUE TITLE
Tutorial 0 doesn't cover the button.style.flex line in example code

### ISSUE THREAD

**Issue by brettcannon** [pybee/toga#568]
The example app at https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html#write-the-app has a line that isn't covered in the tutorial: `button.style.flex = 1` (and I would love to know what t does since the `1` is non-obvious 😉 ).

**Comment by starlord1311** [comment]
can i take up this issue? @brettcannon

**Comment by freakboy3742** [comment]
@brettcannon Thanks for the suggestion. The documentation for Pack [describes what the `flex` attribute does](https://toga.readthedocs.io/en/latest/reference/style/pack.html#flex) - but that's buried pretty deep. A quick explanation (with a link off to the main docs) would be very helpful.

@starlord1311 If you want to take a swing at adding an explanatory note, go right ahead!

**Comment by starlord1311** [comment]
@freakboy3742 @brettcannon can you tell me what i am supposed to do?
