### ISSUE TITLE
pip install -e src/gtk  fails

### ISSUE THREAD

**Issue by russ-hensel** [pybee/toga#574]
## Expected Behavior
Successfully installed xxxx

## Current Behavior
Failed building wheel for pygobject ....
'pkg-config' not found.
and more of similar

## Steps to reproduce

1.cd toga

2. pip install -e src/gtk  fails

## Your Environment
Ubuntu 18.4 in Windows Virtual Box with Anaconda/Spyder installed 

* Python Version 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [x] Linux - distro:   - version: Ubuntu 18.4 in Windows Virtual Box with Anaconda/Spyder installed 
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

Much more documentation is at:
http://www.opencircuits.com/Setup_Toga_with_Spyder  and follow its links 

Note:  This is the first 1/2, error around the install.
In both cases I get something that runs, but there should not be so much pain along the way and
uncertainty that things will keep running.
I would like to help in the development, but am having trouble getting to square 1.

**Comment by danyeaw** [comment]
@russ-hensel Thanks for submitting the issue, hopefully we can help you get Toga going. Did you try to:

... apt-get install pkg-config

**Comment by russ-hensel** [comment]
I did not.  But now I have, still does not seem to work.  Perhaps clue is in PKG_CONFIG_PATH environment variable, something I have not used in the past.  
 I should have noted that I can run the second tutorial, see my other report https://github.com/pybee/toga/issues/575.  Attached is log file.
[more_toga.txt](https://github.com/pybee/toga/files/2255717/more_toga.txt)

**Comment by danyeaw** [comment]
Did you install the dependencies that are in the README?
`sudo apt-get install python3-dev python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev`

**Comment by russ-hensel** [comment]
Did not, but now have, log attached.  Seemed to make a bit of progress.  After that tried
russ@ubuntu-18-base:~/toga$ pip install cairo
Collecting cairo
  Could not find a version that satisfies the requirement cairo (from versions: )
No matching distribution found for cairo
russ@ubuntu-18-base:~/toga$ 

which may not have been a good idea in any case.
[even_more_toga.txt](https://github.com/pybee/toga/files/2255816/even_more_toga.txt)

**Comment by russ-hensel** [comment]
pressed wrong button

**Comment by russ-hensel** [comment]
Ok, I am going to restart this report with some new assumptions: ( for me this is closed for now )
[18_bare_toga55.log](https://github.com/pybee/toga/files/2270730/18_bare_toga55.log)
[18_bare_toga55.log](https://github.com/pybee/toga/files/2270732/18_bare_toga55.log)
[18_bare_toga55.log](https://github.com/pybee/toga/files/2270738/18_bare_toga55.log)



forget anaconda for now
forget spyder for now
notice that venv is the "new" environment manager and use it ( an attempt to install without it on a clean
      machine did not work well.
stay with ubuntu 18.4
follow the docs and all the advice in this thread.
-------------------------------  still get ------------------
error: invalid command 'bdist_wheel'
Failed to build pycairo pygobject

do not know if these matter, my install passes the test suite.

----------------- full install log attached -----------------

plan to go on in this environment for now.
