### ISSUE TITLE
Trying to install development environment and run demo

### ISSUE THREAD

**Issue by russ-hensel** [pybee/toga#575]
## Expected Behavior
follow directions at  https://toga.readthedocs.io/en/latest/ Toga — Toga 0.3.0.dev10 documentation and then be able to run tutorial at: https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html
## Current Behavior
**Lots of errors until I add path changing code in the tutorial to add at the top**

Print( "--- modify sys.path if necessary add until it works ---" )
import sys
for_sys_path     = []
for_sys_path.append( "/home/russ/python03" )
for_sys_path.append( "/home/russ/toga/src" )
for_sys_path.append( "/home/russ/toga/src/core" )
for_sys_path.append( "/home/russ/toga/src/gtk" )
for_sys_path.append( '/home/russ/anaconda3/lib/python3.6/site-packages' )
test_path_add = for_sys_path  [0]

if sys.path[ 0 ] != test_path_add:
    print( "adding to sys.path" )
    sys.path   = for_sys_path + sys.path 
    pass
else:
    print( " sys.path already modified" )

    ...... rest of file  taken from:   https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html

**if path adjustments need to be make could we have some documentation?**

## Steps to reproduce

1. Install Toga as explained at: http://www.opencircuits.com/Setup_Toga_with_Spyder

2. Run tutorial at   https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html in Spyder ( similar behavior in Ipython and terminal Python )

3. Runs fail with various python complaints untill change listed above is made.

## Your Environment
Ubuntu 18.4 in Windows Virtual Box with Anaconda/Spyder installed 

* Python Version 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ x ] Linux - distro:   - version: Ubuntu 18.4 in Windows Virtual Box with Anaconda/Spyder installed 
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

Much more documentation is at:
http://www.opencircuits.com/Setup_Toga_with_Spyder  and follow its links 

Note:  This is the second, 2/2, error around the install.
In both cases I get something that runs, but there should not be so much pain along the way an
uncertainty that things will keep running.
I would like to help in the development, but am having trouble getting to square 1.

**Comment by danyeaw** [comment]
My initial impression of the logs is that this isn't a Toga issue, I don't think you have python setup correctly. The errors are with asyncio importing selectors and other core python errors. I would definitely recommend using a virtualenv as it instructs in the How to contribute to Toga page.

**Comment by russ-hensel** [comment]
I thought using my master environment without a virtual environment would make things simpler, but I can set up a virtual environment.  Do you think the fact that I am installing on top of Anaconda is really the problem and I should get rid of it.  I do want to hang on to the spyder ide, but think I can do that without anaconda.  Would have to build a new virtual machine from scratch to be sure anaconda is gone.

**Comment by russ-hensel** [comment]
Think using venv is more or less required and that the anaconda/spyder idea is premature.
May reopen or post as a new revised bug, but closed for now, see also: #574
