### ISSUE TITLE
Add Canvas Dashed Line Support for Gtk+

### ISSUE THREAD

**Issue by danyeaw** [pybee/toga#581]
Hey PyCon AU 2018 sprinters, and other new contributors - here is a great way to contribute for someone who runs Linux:

Recently @bryall implemented dashed line support for Canvas in the Cocoa backend in #578. It would be great to implement support for dashed lines in Gtk+ as well.

**Comment by Connor-Rowland** [comment]
This seems a little bit over my head, but mind if I take a shot at it?

**Comment by bryall** [comment]
you can do it, let me know if you need any help.

**Comment by Connor-Rowland** [comment]
@bryall I'm not sure if you ran into this problem, but since only the dash pattern is given, how do you find the number of dashes to use to fill the widget?
