### ISSUE TITLE
Tutorial 0 erroring out on Mac OSX High Sierra 10.13.6

### ISSUE THREAD

**Issue by dustinechoes849** [pybee/toga#582]
## Expected Behavior

For it not to error out?
## Current Behavior

Traceback (most recent call last):
  File "/Users/dustinechoes849/PycharmProjects/tutorialjunk/programmie.py", line 24, in <module>
    main().main_loop()
  File "/Users/dustinechoes849/PycharmProjects/tutorialjunk/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/Users/dustinechoes849/PycharmProjects/tutorialjunk/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 95, in _startup
    self._impl = NSApplication.sharedApplication()
TypeError: 'ObjCInstance' object is not callable
## Steps to reproduce

1. Copy-pase example code

2. Run it

## Your Environment

* Python Version (list the specific version number)
Python 3.7
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: High Sierra 10.13.6

* Toga Target (the type of app you are trying to generate)
 
  - [ ] cocoa

This is my first time on here, so I apologize for any goofs I made in this submission. This project just seems really promising and I wanted to help out (as well as find out why it won't work on my system lol)

**Comment by freakboy3742** [comment]
Thanks for the report! This error is one we've seen before - the usual culprit is that you're either: 
(a) running an old version of Toga, or
(b) Using the wrong version of the tutorial for the version of Toga that you've got installed.

When you installed toga, did you use the `--pre` flag? (i.e., `pip install --pre toga`) If you didn't you may find you've got Toga 0.2.15 installed (You can confirm this with `pip freeze`, which will tell what versions are installed). 

The "default" version of the tutorial assumes you're running something from the 0.3.0 development branch. If you've got 0.2.15 installed, you should be able to update by running `pip install -U --pre toga`.

**Comment by dustinechoes849** [comment]
Checked the Project Interpreter settings in PyCharm, and it was using 0.2.15, reinstalled with the `--pre` flag and it's working great, thanks!
