### ISSUE TITLE
No module named 'toga.style'

### ISSUE THREAD

**Issue by MichaPau** [pybee/toga#597]
Trying to run the 'A slightly less toy example' I get a `No module named 'toga.style'` error.

`Package    Version
---------- -------
colosseum  0.1.6  
pip        18.0   
setuptools 40.4.3 
toga       0.2.15 
toga-core  0.2.15 
toga-gtk   0.2.15 
wheel      0.31.1 
(manjaro-toga) [micha@micha-pc bin]$ python ../../../gui/toga/playground.py 
Traceback (most recent call last):
  File "../../../gui/toga/playground.py", line 2, in <module>
    from toga.style.pack import *
ModuleNotFoundError: No module named 'toga.style'`

I have toga 0.2.15 installed

I wasn't able to install the --pre version on my Manjaro dist. (Arch Linux)
(I did run `sudo pacman -S gobject-introspection` beforhand)

I get a `Failed building wheel for pygobject` error when trying to install it in a new venv

**Comment by freakboy3742** [comment]
This error occurs when you're running the wrong version of the tutorial for the version of toga that you have installed. You've got 0.2.15 installed; the "style" attribute was introduced in the 0.3.0 development branch. The default tutorial is based on the development branch.

The tutorial on Read The Docs has a version switcher that will allow you to use the 0.2.15 tutorial; or, you can go digging to work out how to install pygobejct on your flavour of Linux.

**Comment by MichaPau** [comment]
I totally oversaw the little version switcher in the docs, 
as well as other closed issues already present about this *issue* 

After installing the necessary for pygobject system-wide, I am able to run the latest toga version within a virtual environment created with the --system-site-packages flag.
