### ISSUE TITLE
Misleading version compatibility

### ISSUE THREAD

**Issue by Aareon** [pybee/toga#599]
Atleast on Windows hosts, Toga is not yet compatible with Python 3.7 as `pythonnet` has yet to update for it.

It might be worth mentioning this in the README somewhere, or even remove said version from the shield.

**Comment by Aareon** [comment]
I’ll leave this here for tracking progress.
https://github.com/pythonnet/pythonnet/pull/698

As far as the rest of the dependencies, I haven’t looked over them, I just noticed that the build for `toga` failed as soon as I got to `pythonnet`

**Comment by denfromufa** [comment]
@Aareon official python 3.7 support for pythonnet has been merged to master branhc, no pypi release yet.

**Comment by Aareon** [comment]
I see. Thank you for clearing that up.
