### ISSUE TITLE
Just failed to install

### ISSUE THREAD

**Issue by f-lima** [pybee/toga#625]
## Expected Behavior
Succesfull toga instalation

## Current Behavior
Collecting toga
  Using cached https://files.pythonhosted.org/packages/04/73/3ded37ce19d9657be425fffd1ee76d7cde26395baab17c01548db0230927/toga-0.3.0.dev11-py3-none-any.whl
Collecting toga-gtk==0.3.0.dev11; sys_platform == "linux" (from toga)
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Requirement already satisfied: gbulb>=0.5.3 in ./venv/lib/python3.6/site-packages (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
  Using cached https://files.pythonhosted.org/packages/00/17/198a9d0eb0e89b5c7d2a9b4437eb40d62702ab771030cd79fc7141cb0d30/PyGObject-3.30.1.tar.gz
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
  Using cached https://files.pythonhosted.org/packages/a6/54/23d6cf3e8d8f1eb30e0e58f171b6f62b2ea75c024935492373639a1a08e4/pycairo-1.18.0.tar.gz
Requirement already satisfied: toga-core==0.3.0.dev11 in ./venv/lib/python3.6/site-packages (from toga-gtk==0.3.0.dev11;sys_platform == "linux"->toga)
Requirement already satisfied: travertino>=0.1.0 in ./venv/lib/python3.6/site-packages (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11; sys_platform == "linux"->toga)
Building wheels for collected packages: pygobject, pycairo
  Running setup.py bdist_wheel for pygobject ... error
  Complete output from command /home/flima/dev/db/herbalife/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7sgste6l/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqo04l7lgpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pygobject
  Running setup.py clean for pygobject
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /home/flima/dev/db/herbalife/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7sgste6l/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpiy8ac30_pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pygobject pycairo
Installing collected packages: pycairo, pygobject, toga-gtk, toga
  Running setup.py install for pycairo ... error
    Complete output from command /home/flima/dev/db/herbalife/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7sgste6l/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lrhk99zq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/flima/dev/db/herbalife/venv/include/site/python3.6/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.6/cairo
    running build_ext
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'cairo' found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.

    ----------------------------------------
Command "/home/flima/dev/db/herbalife/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7sgste6l/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lrhk99zq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/flima/dev/db/herbalife/venv/include/site/python3.6/pycairo" failed with error code 1 in /tmp/pip-build-7sgste6l/pycairo/

## Steps to reproduce
pip install --pre toga

## Your Environment

* Python Version (list the specific version number)
Python 3.6.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ X ] Linux - distro: Ubuntu 18.04.1 LTS
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

**Comment by freakboy3742** [comment]
Thanks for the report. That's an error I haven't seen before, but it suggests that bdist_wheel is required for some reason. However, there's nothing in Toga that should require that. Can you confirm if you're able to `pip install pygobject` by itself?

**Comment by f-lima** [comment]
Solved!
After install dozens of packages required to install pygobject, I could finally install Toga.
I had to install libraries using sudo apt-get required to install pygobject before the command pip install. 
Thanks for your help.
