### ISSUE TITLE
AttributeError : 'Table' object has no attribute 'insert'

### ISSUE THREAD

**Issue by brendanlegacy** [pybee/toga#630]
Using Python 3.6.5 on Windows 10 w/ toga 0.3.0 dev 11:

The API reference for Toga shows an insert attribute for the Table that allows you to insert additional rows. 

![image](https://user-images.githubusercontent.com/44812977/50022959-73104b80-ffa3-11e8-8924-72e1b7846448.png)

However, no attribute exists and you get an "AttributeError : 'Table' object has no attribute 'insert'" if you attempt to do so. 

Is this something that will be included in future releases? It would be super helpful.

**Comment by Ocupe** [comment]
@brendanlegacy 

The table uses a data source inside. So you can't insert something into the table itself but you have to insert it into the data source of the table. This should work:
```
table.data.insert(None, 'value 1', 'value 2')
```

I would recommend you take a look at a working example [here](https://github.com/pybee/toga/blob/master/examples/table/table/app.py)

**Comment by TommieEdwardBerry** [comment]
Ocupe,  Thanks for that last entry, that example worked like a champ.
The only issue I had, is that in the on_select handler I have to change This:
"You selected row: {}".format(row.title)
to this:
str("You selected row: %s"%(row.title))

It worked in your example, but in mine it did not, giving error that row had no attribute "title"

**Comment by TommieEdwardBerry** [comment]
Is there a way to auto size the columns to fit the longest text?
