### ISSUE TITLE
App Header for Android

### ISSUE THREAD

**Issue by Brianzhengca** [pybee/toga#639]
is it possible to create android app header like this???
![image](https://user-images.githubusercontent.com/30914529/51621064-90143480-1ee8-11e9-94aa-a62c1cb56046.png)

**Comment by Brianzhengca** [comment]
Can I also add buttons on the header bar for app navigation???

**Comment by freakboy3742** [comment]
Android applications *do* have a header bar like the one you've described; following the general Toga philosophy, specifically adding actions to the title bar isn't a feature that is likely to be added, but adding actions to the app that manifest as buttons on the title bar would be.

However, as I indicated on #638, the bigger issue at the moment is maturity and stability. The Android backend isn't currently working at all, and the widget selection is currently very meagre.

**Comment by Brianzhengca** [comment]
ok thank you!!!
