### ISSUE TITLE
Is it possible to get the current GPS-location on iOS?

### ISSUE THREAD

**Issue by gressh0ppe** [pybee/toga#642]
## Expected Behavior
I'm currently working on a iOS app that's based around the current position of the user.
As I think the native support of Beeware is superior to the clunky designs that often is the result of other cross-platform Python frameworks, I was wondering if there is any way to get the coordinates (along with user-permissions)? I have been reading up on Rubicon, but I haven't found anything that could help me. 
And if it is not available on iOS, is it available for Android?

## Your Environment

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: 10.14.2
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [x] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [x] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by danyeaw** [comment]
@gressh0ppe This isn't currently supported on iOS or Android yet, but we definitely would like it to be. Would you be interested in contributing a widget to support this?

**Comment by gressh0ppe** [comment]
@danyeaw I'd love to, but I doubt I have the skills necessary to do so. I'll look into it anyways!

**Comment by danyeaw** [comment]
@gressh0ppe I put together an overview of how to build a widget on my blog https://dan.yeaw.me/posts/gui-widget-for-beeware/

Come chat with us on gitter if you have further questions. I'm going to go ahead and close this issue. Thanks for submitting it!
