### ISSUE TITLE
Not running on windows 10 64 bit

### ISSUE THREAD

**Issue by PROuserR** [pybee/toga#644]
failed with error code 1 in C:\Users\USER\AppData\Local\Temp\pip-install-8gcqf8cb\pythonnet\

**Comment by freakboy3742** [comment]
It's difficult to diagnose anything with the information you've provided - closing this ticket on that basis.

My guess is that you're using Python 3.7. Pythonnet hasn't publisehd an update for Python 3.7, so you have to have a compiler toolchain installed and configured for that to work. If that's *not* the problem, please open another ticket with more details.
