### ISSUE TITLE
Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt

### ISSUE THREAD

**Issue by NilsRG** [pybee/toga#65]
Running toga-demo on Ubuntu 16.04, gives a traceback in the shell: (The GUI is shown and seems to work despite the error)

Traceback (most recent call last):
  File "/home/nils/.local/lib/python2.7/site-packages/toga_gtk/widgets/container.py", line 61, in do_size_allocate
    widget._impl.size_allocate(child_allocation)
TypeError: argument allocation: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt

**Comment by freakboy3742** [comment]
This has been corrected in the 0.2.2 release.
