### ISSUE TITLE
Clearly state "Python 3 only ".

### ISSUE THREAD

**Issue by TiberiumPY** [pybee/toga#66]
Clearly state in README and while installing from PIP (because user would install it from Python 2, and then, trying to run it - oh, no, this is python 3 only).
I think the best way would be to check Python version in setup.py

**Comment by freakboy3742** [comment]
Fair comment. The Python 3 only status is flagged in setup.py; however, clearer docs and a safety switch wouldn't go astray.

**Comment by freakboy3742** [comment]
Added documentation in a2fcdfd3a, and install protection in 8758ab4c.
