### ISSUE TITLE
Can't run toga-demo on Arch

### ISSUE THREAD

**Issue by elvis-sik** [pybee/toga#73]
I use Arch Linux. I use Anaconda distribution.
I create a fresh conda environment (equivalent a global system environment) with Python 3, activate it, and do

```
$ pip install toga
$ pip install toga-demo
$ toga-demo
/home/elvis/miniconda3/bin/python: symbol lookup error: /usr/lib/libgtk-3.so.0: undefined symbol: g_log_structured
```

**Comment by marcmolla** [comment]
It seems that some dependencies are missing. You can check the requirements [here](https://github.com/pybee/toga/blob/master/src/gtk/README.rst)

**Comment by voltagex** [comment]
I was able to run toga-demo by doing the following in a VM:

* Install Arch 2017.04.01
* Install virtualbox DKMS modules
* Install GNOME3 and GDM
* Install python-pip and python-virtualenv (defaults to 3 in Arch)
* Create and activate a virtualenv
* Install and run toga-demo

It looks like that library is provided by the `gtk3` package so you may want to upgrade that and optionally miniconda to match.

I think we should close this issue.

**Comment by freakboy3742** [comment]
Closing on @voltagex's recommendation; if you're still seeing this problem, please reopen with details.
