### ISSUE TITLE
Make cocoa apps have app name as title of first menu item (not "python")

### ISSUE THREAD

**Issue by jrwdunham** [pybee/toga#77]
Is this easily doable? I haven't been able to figure it out. Any help much appreciated.

**Comment by freakboy3742** [comment]
It is; but not if you start the app from the command line. The name of the app in the menubar is the name of the executable bundle; if you use the command line to start the app, that's "python". 

However, if you wrap your project up in an app bundle, you can provide app metadata and set the app to be whatever you want. Briefcase is a project that makes this relatively simple - just define your setup.py, and the rest is auto generated for you.

**Comment by jrwdunham** [comment]
Thanks! Moving on to Briefcase now to try that out!

**Comment by jrwdunham** [comment]
Excellent. Confirmed that Briefcase fixes this. Feel free to close this.

**Comment by freakboy3742** [comment]
Excellent; closing. 

That said, if anyone can work out a magic combination of invocations that allows setting the app name *without* wrapping in an app bundle, I'd happily integrate that change.
