### ISSUE TITLE
Add API for defining actions and menus.

### ISSUE THREAD

**Issue by freakboy3742** [pybee/toga#81]
Applications often have menus; Toga should have an API to define menus. However, it's not as simple as just adding a "add menu, add item to menu" API. 

Toga is trying to model a broader "capture the concept, not the widget" philosophy. A menu is a specific manifestation of a user interface (A very common one, mind - but a specific rendition). Mobile interfaces, for example, generally wont have them - at least, not in the same way as they are rendered on desktops. 

What *is* common, though, is the idea of an "action" that can be performed. That action might have a keyboard shortcut, or operate on a context (such as a currently selected item). There might be an icon to describe the action. The action can be enabled or disabled depending on context. And, obviously, there's the body of code that is actually invoked when the action is activated.

That action might be installed in a menu bar, or in a toolbar, or in a context menu; or in all three. But the *action* is independent of exactly how it is accessed; although the definition of action might influence how it is displayed.

So - while an "add menu to menubar", and "add item to menu" will be needed - the "item" should be an action that encompasses being enabled, disabled, named, and invoked. 

A related example - some actions - such as "quit", "print", "preferences" - have locations that are platform-dependent. Quit appears under "File" on windows; but under the application menu on macOS. Part of this "action" specification is to provide for certain key actions that can "find a home" by virtue of being defined at all, rather than needing to be placed on a specific menu.

**Comment by Just-Sieb** [comment]
[Electron](http://electron.atom.io/docs/api/menu/) does a fairly good job at providing an API to add menus to Linux, Windows, and macOS. Their definition is JSON based which is more of a JavaScript way of doing than a Pythonic one. 

As far as mobile goes, I could see having the menu being an abstracted way to add sidebar navigation on an Android app. That is the closest equivalent that I can think of for Android. 
![](https://raw.githubusercontent.com/rudsonlive/NavigationDrawer-MaterialDesign/master/Screenshot/Screenshot_01.png)

I am not not familiar with the design patterns on iOS, but I would assume there would be some similar design convention that is typically a menu.

**Comment by jrwdunham** [comment]
Nice explanation and example freakboy3742 and Just-Sieb. So it sounds like we
need to build a list of "actions" that are common to all GUI applications,
meaning that all such apps are able, in principle, to implement those actions.
Then a developer could simply write something like
``app.add_action(TogaAction('quit'))`` and the appropriate thing would happen
on Android, iOS, MacOS, etc.

That said, is it not still desirable to have Toga expose "lower level" UI
classes like `Menu` and `MenuItem` even if, ideally, we want developers to use
the higher-level action-building interface? On the one hand, the action
interface would itself presumably make use of the menu(item) interface for desktop
apps and, on the other hand, developers may want that level of control and/or
may want to target a certain subset of platforms.

**Comment by Just-Sieb** [comment]
Building on what @jrwdunham said I could see there being a generic menu item class that adds items to the typical menu spot in each platform. We could also have various common action sub-classes that could easily be added to a toga app with common actions on each app such as quiet, copy/paste, and share. Copy and paste on mobile is typically handles by holding finger down on text, but under an edit option in windows. To me this seems to be a good compromise between having easy options for the basic common actions but also have options to customize how needed.

Though I can also see times where I would like to modify what is triggered on each platform. Maybe something along these lines.
```python
#option 1
menu_choice = menu_item(name="Choice", action=default_func, android=android_func, ios=ios_func, win32=win32_func)
app.menu.add_action(menu_choice)

#option 2
menu_mobile_choice = menu_item(name="Choice", action=mobile_choice_func, platforms=['android', 'iOS'])
menu_desktop_choice = menu_item(name="Choice", action=desktop_choice_func, platforms=['win32', 'cocoa', 'gtk'])
app.menu.add_action(menu_mobile_choice)
app.menu.add_action(menu_desktop_choice)
```
Option ones has less lines of code but the lines will probably be longer for more complicated menu items.

Any other thoughts or suggestions?

**Comment by goanpeca** [comment]
Worth [reading](http://doc.qt.io/qt-5/qml-qtquick-controls-action.html)?

**Comment by freakboy3742** [comment]
This has been mostly implemented. Some platforms need some more work, but the basic APIs are now in place.
