### ISSUE TITLE
API to disable buttons?

### ISSUE THREAD

**Issue by SilverWingedSeraph** [pybee/toga#91]
Most platforms have a "disabled" state for their buttons (in fact I don't know of any that don't) - they become 'greyed out' and can't be clicked. It would be awesome to have an API for this; i.e. `button.disable()` and `button.enable()` or `set_abled(enabled=True)` or `set_abled(enabled=False)`.

**Comment by freakboy3742** [comment]
Absolutely agreed. The API that is there is a bare minimum, and not at all finalised. An enable/disable API would be an obvious thing to add.

**Comment by freakboy3742** [comment]
Resolved by #112
