### ISSUE TITLE
Won't run on Sierra

### ISSUE THREAD

**Issue by RantyDave** [pybee/toga#94]
The first problem is that it complains that App doesn't implement open_document(), but that's easy enough to fix.

More of a problem is that it won't start on macOS 10.12.2, Python 3.6.0 ('brew install python3'). The complaint is:

```
File "/usr/local/lib/python3.6/site-packages/toga_cocoa-0.2.4-py3.6.egg/toga_cocoa/app.py", line 103, in _startup
    self.app_menuItem = self.menu.addItemWithTitle_action_keyEquivalent_(app_name, None, '')
  File "/usr/local/lib/python3.6/site-packages/rubicon_objc-0.2.3-py3.6.egg/rubicon/objc/objc.py", line 809, in __call__
    return self.method(self.objc_id, *args)
  File "/usr/local/lib/python3.6/site-packages/rubicon_objc-0.2.3-py3.6.egg/rubicon/objc/objc.py", line 778, in __call__
    result = f(objc_id, self.selector, *(from_value(arg) for arg in args))
ctypes.ArgumentError: ("argument 3: <class 'TypeError'>: wrong type", 'selector = addItemWithTitle:action:keyEquivalent:', "argtypes =[<class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>]", 'encoding = @40@0:8@16:24@32')
```

I have the latest xcode installed and built by git cloning 0.2.5.dev1, changing the instances of the word python to read python3, and running `release.sh build` then I think `python3 setup.py install`. As you can tell it was all a bit of a bunfight :(

**Comment by freakboy3742** [comment]
I haven't had a chance to look at Python 3.6 support yet - it was only released a couple of weeks ago. 3.5 is the most recent version that I can confirm works.

The error that you report is consistent with the wrong template being used. Python 2.7, 3.4 and 3.5 each require a slightly different bootstrap script; it looks like you're using the Python 2.7 template. The right template should be picked up by Briefcase - It uses the version of Python that was used to execute Briefcase to pick the right template.

This also explains the other problem you've found - You definitely *shouldn't* need to change the source to say "python3". The code (and instructions) all assume you're using a virtual environment, in which a simple "python" invocation will start the right interpreter.

I haven't done any testing on Sierra yet, but I don't think *Sierra* is the underlying cause of any the problems you're seeing here. The open_document thing is definitely a problem - but that exists on Yosemite as well.

**Comment by RantyDave** [comment]
Sorry for the delay. Works fine with python.org's distribution of 3.5.2 so it's obviously something to do with brew.
