### ISSUE TITLE
Create a code style page for contributors

### ISSUE THREAD

**Issue by tonybaloney** [pybee/toga#99]
It's always handy for new contributors to have a set of guidelines on how code should be laid out. Everyone has their own personal style and it avoids any difficult conversations being able to point at the guide.

1. Docstrings, use Google Style, NumPy Style, or just PEP257 + comments - Perhaps leverage napoleon (http://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html)
2. Use double quotes in docstrings, start with a line break for multi-line
3. Method argument naming and casing, e.g. https://github.com/pybee/toga/blob/master/src/core/toga/interface/app.py#L69
4. PEP8 compliance
5. Use of linters like pylint
6. Expectations for unit tests
7. Specification of `__all__` required?
8. Preference of relative imports v.s. absolute. I can see you prefer relative.
9. Other pet peeves

**Comment by tonybaloney** [comment]
Ref #98

**Comment by glasnt** [comment]
FYI we have a yak to try and address some of these things by using https://github.com/pybee/beefore

**Comment by freakboy3742** [comment]
We also have default PEP8 settings in other BeeWare projects, so we could potentially turn on CI for the sole purpose of running code style checks (until, of course, we actually get unit tests...)

**Comment by freakboy3742** [comment]
We now enforce PEP8 style with BeeFore, so this *should* be a non-issue.
